### ISSUE TITLE
Runtime error on iOS

### ISSUE THREAD

**Issue by yadutechnologies** [dpa99c/cordova-custom-config#103]
I have installed this plugin@3.1.2. 
I have added this config code in `<platform name="ios">` tag 
`<config-file platform="ios" target="[AppName]-Info.plist" parent="LSApplicationQueriesSchemes">`
            `<array>`
                `<string>whatsapp</string>`
                `<string>fb</string>`
            `</array>`
        `</config-file>`
When I run the application thorugh Xcode on my iPhone 5 I got a runtime error and the app stuck at that point. 
Please Help.
![screen shot 2017-02-22 at 6 20 07 pm](https://cloud.githubusercontent.com/assets/19183024/23212268/e9931b28-f92b-11e6-976f-9cfac961ef5f.png)

**Comment by dpa99c** [comment]
These plist keys are unlikely to be the cause of the runtime error. The [example project](https://github.com/dpa99c/cordova-custom-config-example) inserts some [dummy url schemes](https://github.com/dpa99c/cordova-custom-config-example/blob/master/config.xml#L161) and even appending your config block to the config.xml, this builds and runs fine (see screenshot below).

I would suggest you also try building and running the example project, inserting your custom config block to validate that this builds and runs OK.

![screencap](https://cloud.githubusercontent.com/assets/2345062/23329864/c6b1d0ea-fb38-11e6-8fe1-7fe5bf588b7c.jpg)

**Comment by yadutechnologies** [comment]
Thanks for reply, 
I will check that.
