### ISSUE TITLE
ios-XCBuildConfiguration-IPHONEOS_DEPLOYMENT_TARGET does not work unless buildType is specified

### ISSUE THREAD

**Issue by kukikiloke** [dpa99c/cordova-custom-config#104]
Steps:
1. Include `<preference name="ios-XCBuildConfiguration-IPHONEOS_DEPLOYMENT_TARGET" value="9.0"  />` in ios platform block in config.xml
2. Build the project with cordova CLI and open the XCode project with XCode.
3. Check the deployment target under Build. It's still 8.0 (Cordova default)
4. Add attribute `buildType="debug"` to the preference tag and rebuild then the deployment target is now 9.0 (correct!)

**Comment by dpa99c** [comment]
I'm unable to reproduce the result you describe by following the steps above. Using the most recent plugin version, the result is a deployment target of `9.0` - see [this screencapture](http://ge.tt/2c3c0Mj2).

**Comment by dpa99c** [comment]
Closing due to no response by OP
