### ISSUE TITLE
AndroidManifest application name replaces all children

### ISSUE THREAD

**Issue by vaprea** [dpa99c/cordova-custom-config#105]
Using version _3.0.14_ with configuration as the following  

``<config-file target="AndroidManifest.xml" mode="add">     
    <application android:name="MyApp" />     
</config-file>  
``
inserts a new application tag and replaces all childs, any
idea how to fix? 

Tnx

**Comment by dpa99c** [comment]
Update to latest version - 3.1.2 - and retest.

3.0.14 is very old and the bug has probably been fixed.

**Comment by vaprea** [comment]
Thank you!
