### ISSUE TITLE
Failed to install 'cordova-custom-config':undefined

### ISSUE THREAD

**Issue by zwacky** [dpa99c/cordova-custom-config#111]
```
# ionic plugin add cordova-custom-config

Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" for android
cordova-custom-config: npm dependencies missing - installing
Failed to install 'cordova-custom-config':undefined
Error: Error installing npm dependencies: Error: Command failed: npm install cordova-custom-config
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "cordova-custom-config" under a package
npm ERR! also called "cordova-custom-config". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zwacky/.npm/_logs/2017-04-12T13_11_47_627Z-debug.log

```

also throws an error when trying to use `ionic plugin add cordova-custom-config@3.1.4`. version 2.0.3 works fine.

**Comment by dpa99c** [comment]
This has been reported before (#86) though I haven't been able to reproduce it, but it seems to be a problem when attempting to install into a project which previously contained an old version of the plugin.

Try cleaning out previous remnants: `rm -Rf node_modules/cordova-custom-config` and `rm -Rf plugins/cordova-custom-config` then install.

If still having issues, install with [new cordova-fetch option](https://cordova.apache.org/news/2016/05/24/tools-release.html)

    cordova plugin add cordova-custom-config --fetch

(not sure if ionic CLI supports the `--fetch` flag yet)

**Comment by zwacky** [comment]
Hey @dpa99c, I tried all variations and still get an error.

```
# cordova plugin add cordova-custom-config --fetch

Error: Failed to fetch plugin cordova-custom-config via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
```

**Comment by dpa99c** [comment]
Seems like you have some weirdness with your dev environment if it can't find the plugin via the registry - [it's there](https://cordova.apache.org/plugins/?q=cordova-custom-config). Here's what I get:

    $ cordova -v
    6.5.0

    $ cordova plugin add cordova-custom-config --fetch --verbose
    No scripts found for hook "before_plugin_add".
    No version specified for cordova-custom-config, retrieving version from config.xml
    Calling plugman.fetch on plugin "cordova-custom-config@*"
    Running command: cmd "/s /c "G:\Users\dpa99_000\AppData\Roaming\npm\npm.cmd install cordova-custom-config@*""
    Command finished with error code 0: cmd /s /c "G:\Users\dpa99_000\AppData\Roaming\npm\npm.cmd install cordova-custom-config@*"
    Copying plugin "D:\Git\cordova-custom-config-example\node_modules\cordova-custom-config" => "D:\Git\cordova-custom-config-example\plugins\cordova-custom-config"
    Calling plugman.install on plugin "D:\Git\cordova-custom-config-example\plugins\cordova-custom-config" for platform "android
    Installing "cordova-custom-config" for android
    Running command: cmd "/s /c "D:\Git\cordova-custom-config-example\platforms\android\cordova\version.bat""
    Command finished with error code 0: cmd /s /c "D:\Git\cordova-custom-config-example\platforms\android\cordova\version.bat"
    Finding scripts for "before_plugin_install" hook from plugin cordova-custom-config on android platform only.
    No scripts found for hook "before_plugin_install".
    Install start for "cordova-custom-config" on android.
    Beginning processing of action stack for android project...
    Action stack processing complete.
    Install complete for cordova-custom-config on android.
    Finding scripts for "after_plugin_install" hook from plugin cordova-custom-config on android platform only.
    Executing script found in plugin cordova-custom-config for hook "after_plugin_install": plugins\cordova-custom-config\hooks\resolveDependencies.js
    Resolving module name for child_process => child_process
    Resolving module name for fs => fs
    Resolving module name for path => path
    Resolving module name for q => q
    cordova-custom-config: npm dependencies already installed
    No scripts found for hook "after_plugin_add".

    $ cordova prepare android
    cordova-custom-config: Skipping auto-restore of config file backup(s)
    cordova-custom-config: Applied custom config from config.xml to D:\Git\cordova-custom-config-example\platforms\android\AndroidManifest.xml

**Comment by dpa99c** [comment]
Closed due to no response from OP

**Comment by zwacky** [comment]
```
$ cordova -v
6.5.0

$ node -v
v6.9.5

$ npm -v
4.4.4
```

the thing that baffles me the most is this:
```
$ ionic plugin add cordova-custom-config

[...]

cordova-custom-config: npm dependencies missing - installing

npm ERR! Refusing to install package with name "cordova-custom-config" under a package
npm ERR! also called "cordova-custom-config". Did you name your project the same
npm ERR! as the dependency you're installing?
```

can this be caused by other plugins somehow?

**Comment by dpa99c** [comment]
> can this be caused by other plugins somehow?

You could eliminate that as a possible cause by trying with the [example project](https://github.com/dpa99c/cordova-custom-config-example) which is what I tested it with: clone the repo and try `ionic plugin add cordova-custom-config` then see if it works.

**Comment by zwacky** [comment]
The issue was on my part all along. my package.json was completely off. I solved it by creating a new one via `ionic state save`.

I think #86 must have the same package.json issue that I had or that they run `cordova plugin add cordova-custom-plugin` in the actual cordova-custom-plugin directory(?!).
Cheers!

**Comment by vishwaa17** [comment]
iam getting an error like this after adding the custom-config 
cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to D:\location\plat
forms\android\AndroidManifest.xml
cordova-custom-config: Error updating config for platform 'android': Cannot read
 property 'charAt' of undefined
