### ISSUE TITLE
cordova-custom-config and ionic cloud build problem

### ISSUE THREAD

**Issue by luckylooke** [dpa99c/cordova-custom-config#112]
Maybe you can help with this:
https://github.com/driftyco/ionic-cloud-angular/issues/26

Related:
https://github.com/driftyco/ionic-cloud/issues/196
https://github.com/driftyco/ionic-app-scripts/issues/876

Thanks

**Comment by dpa99c** [comment]
Does Ionic Cloud support plugin hook scripts? I can't find any reference in their documentation that confirms this or not.

Because [Phonegap Build and Intel XDK do not](https://github.com/dpa99c/cordova-custom-config#important-note-for-phonegap-build--intel-xdk) and this prevents this plugin (which is comprised solely of hook scripts) for working.

**Comment by luckylooke** [comment]
Hm.. I dunno.. I will try to ask them.

**Comment by luckylooke** [comment]
I have found the answer: https://docs.ionic.io/services/package/#hooks
They dont support hooks.. :/ 
But maybe you can submit your hook.. 
> See README.md for documentation and CONTRIBUTING.md if you’d like to submit a hook.

What do you think? :)

**Comment by dpa99c** [comment]
This plugin consists of [multiple hooks](https://github.com/dpa99c/cordova-custom-config/tree/master/hooks) and [npm dependencies](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L31) so submitting a single custom hook is not going to work.

The raison d'être for this plugin is for automated customisation of the native platform projects in a local build environment. Therefore I think, if Ionic Cloud doesn't support arbitrary plugin hooks, then support for it is out-of-scope and I won't be attempting to support it.

What I will do is update the documentation to make clear the Ionic Cloud is an unsupported environment (in addition to Phonegap Build, Intel XDK and Telerik Appbuilder).

**Comment by luckylooke** [comment]
Ok, at least we all know now where the problem is. Thanks anyway 👍 
> update the documentation
can help other ionic developers coming to your plugin :)
