### ISSUE TITLE
Grafana 4.2 update IndexBy is not a function

### ISSUE THREAD

**Issue by JorgeJavier94** [dpa99c/cordova-custom-config#113]
I upgraded Grafana 3.x.x to 4.2.0, and since then I have the error "_.indexBy is not a function" 
I am kinda new to this and I can't seem to find why it does that.
![2017-05-01 10_58_06-grafana - cti16pvdivsc01 - vcenter console](https://cloud.githubusercontent.com/assets/28263285/25583128/728dfcce-2e5e-11e7-9e29-c33958afbab4.png)

I've been using it with Zabbix, on CentOS and InfluxDB and never had any trouble with the previous version. I ran a `yum update grafana` just in case but still nothing. Any ways to help me out? Do you actually need more information?

Thanks!

**Comment by dpa99c** [comment]
This error in `grafana` bears no relation to the Cordova plugin in this repo - `cordova-custom-config`
