### ISSUE TITLE
can I use this plugin for this?

### ISSUE THREAD

**Issue by paredesivan** [dpa99c/cordova-custom-config#116]
Hi. I have a problem. I have a base application using ionic/cordova for android, and I need to develop applications derived from it, but that have different: Package name, Keystore (password alias, etc), Css and maybe html, Some images (especially logos), and some texts (especially titles).

can I use this plugin for develop on an application and when compiling, to generate several different apks. I know there are flavors in android, but I do not know how to use them in an apache cordova application

**Comment by dpa99c** [comment]
No, that's not what this plugin is intended for.

Personally, I would put in place a CLI-driven build process using Grunt or Gulp to assemble the relevant files into the Cordova project folder before building with the Cordova CLI.

**Comment by paredesivan** [comment]
@dpa99c thanks
