### ISSUE TITLE
Error: Cannot read property 'getConfigXml' of undefined

### ISSUE THREAD

**Issue by MaxBreida** [dpa99c/cordova-custom-config#118]
Hi,

since around 20 days i can't build my android app, probably since after the version bump to 4.0.0 of this plugin. At first there were 2 dependencies of cordova-custom-config missing which weren't missing before, tostr and elementtree. After adding these dependencies I am facing the error stated below: 

```
Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" for android
Installing "cordova-custom-config" for ios
cordova-custom-config: Skipping auto-restore of config file backup(s)
Error: Cannot read property 'getConfigXml' of undefined
[15:23:20] 'cordova-add-plugins' errored after 18 s
[15:23:20] Error: Command `cordova prepare` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I found another post [at another cordova forum](https://forums.cocoon.io/t/error-at-compilation-cannot-read-property-getconfigxml/5725) with the same problem, uninstalling the plugin fixed it for him.

**Comment by cozzbie** [comment]
Getting the same error. Not sure what I did wrong because project has been compiling fine prior.

**Comment by dpa99c** [comment]
I'm not able to reproduce this issue.

What version of `cordova` are you using? `cordova-custom-config@4` relies on using `cordova-fetch` to install the plugin dependencies: see the [Installation](https://github.com/dpa99c/cordova-custom-config#installation) section for details. If you're unable to use `cordova@7` for some reason, you are best pinning the version to `cordova-custom-config@3`.

If you are using `cordova@7+` (or `cordova@6.2+` with the `--fetch` option) and still encounter this error, then please run the operation that's failing with the `--verbose` option, and post the resulting console output here.

**Comment by cozzbie** [comment]
And uninstall and reinstall fixed it. I think what happened was that I installed a plugin that relies on the plugin and it seems like it corrupted it somehow.

**Comment by dpa99c** [comment]
@MaxBreida does uninstall/reinstall also fix it for you?

**Comment by touficbatache** [comment]
This issue is occuring with me too. I can't run --fetch as I am using an online service to compile my app: http://cocoon.io

**Comment by dpa99c** [comment]
@touficbatache [As documented](https://github.com/dpa99c/cordova-custom-config#important-note-for-remote-build-environments):

> This plugin is intended for the automated application of custom configuration to native platform projects in a **local build environment**.

**Comment by touficbatache** [comment]
Hmm, can't this be done in any way with cocoon.io?

**Comment by dpa99c** [comment]
@touficbatache You can try using `cordova-custom-config@3` which doesn't rely on `cordova-fetch`, but obviously doesn't contain the latest features/bugfixes

**Comment by touficbatache** [comment]
Oh okay, thank you!
