### ISSUE TITLE
Keep going if failed on xcode

### ISSUE THREAD

**Issue by oak-tree** [dpa99c/cordova-custom-config#12]
We have two platform Android and iOS. But no every developer has mac so not every one has xcode installed. Therefore I suggest the plugin will keep working even if failed to find xcode module.

Thanks

**Comment by dpa99c** [comment]
v1.1.6 should resolve this for you - if an error is encountered while processing a given platform, it will continue to process other platforms unless the `cordova-custom-config-stoponerror` preference is set. 

Note that I will be adding a few more fixes/features to this version before I publish it to npm, so for now you can install it directly from the repo: `cordova plugin add https://github.com/dpa99c/cordova-custom-config`
