### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by listepo** [dpa99c/cordova-custom-config#120]
In the Ionic Package I have error: Error: Error loading dependencies - ensure the plugin has been installed via cordova-fetch or run 'npm install cordova-custom-config': Cannot find module 'lodash'

```
global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

System:

    Node       : v7.7.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 5.3.0
```

**Comment by dpa99c** [comment]
Closed due to no response from OP
