### ISSUE TITLE
AndroidManifest.xml only showing last addition of each type

### ISSUE THREAD

**Issue by rodneyweaver** [dpa99c/cordova-custom-config#121]
I know this is a really similar issue to at least 2 other issues, but the root causes of those don't seem to be applicable here.  I really hope I'm just missing something easy.

In my config.xml I have this block of code:
`<config-file parent="application/activity/[@android:name='MainActivity']" target="AndroidManifest.xml">`
`            <preference android:name="AndroidPersistentFileLocation" android:value="Internal" />`

`            <intent-filter android:label="@string/launcher_name">`
`                <action android:name="android.intent.action.MAIN" />`
`                <category android:name="android.intent.category.LAUNCHER" />`
`            </intent-filter>`

`            <intent-filter android:name="ShareIntent" android:label="ShareIntent">`
`                <action android:name="android.intent.action.SEND" />`
`                <category android:name="android.intent.category.DEFAULT" />`
`                <data android:mimeType="*/*" />`
`            </intent-filter>`

`            <intent-filter android:name="EmailIntent" android:label="EmailIntent">`
`                <action android:name="android.intent.action.SEND" />`
`                <category android:name="android.intent.category.BROWSABLE" />`
`                <category android:name="android.intent.category.DEFAULT" />`
`                <data android:host="gmail-ls" />`
`                <data android:scheme="content" />`
`                <data android:mimeType="application/octet-stream" />`
`            </intent-filter>`
`        </config-file>`

`        <config-file target="AndroidManifest.xml">`
`            <uses-permission android:name="android.permission.WAKE_LOCK" />`
`            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`
`        </config-file>`

Only the last intent-filter is being added to my AndroidManifest.xml.  I've verified this by changing the order that they're declared in config.xml.  Similarly, only the last uses-permission is being added.

I've read in other issues that not declaring the unique identifier can cause this, but I have labels defined for each intent-filter and the issue persists.  Any idea what could cause this?

**Comment by dpa99c** [comment]
You have not set a parent attribute on the `config-file` tags and this is the cause of your issues. 
For example, for `uses-permission` entries, it should be:

	<config-file target="AndroidManifest.xml" parent="/*">
		<uses-permission android:name="android.permission.WAKE_LOCK" />
		<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	</config-file>

The parent attribute is required so the script can identify which parent elements can have valid multiple child instances of a given tag name.

**Comment by rodneyweaver** [comment]
Oops, I realize that I didn't add that back in when I was testing a few things.  Thank you for pointing that out.

I restored the `parent="/*"` like in your example, which fixes the issue for the permissions.  The previous `config-file` tag has a parent specified but is still exhibiting the issue.

Some interesting things I've noticed about the `config-file` that includes all of the `intent-filters`:

1) When the declaration looks like this: `<config-file parent="application/activity/[@android:name='MainActivity']" target="AndroidManifest.xml">` only the `EmailIntent` is added.

2) When the declaration looks like this `<config-file parent="application/activity/*" target="AndroidManifest.xml">` for some reason the `EmailIntent` gets nested inside of the `@string/launcher_name` tag.

3) Changing the declaration to `<config-file parent="application/activity" target="AndroidManifest.xml">` results in the same scenario as 1).

**Comment by rodneyweaver** [comment]
@dpa99c I wanted to bump this in case you didn't see my response.  I'm still having trouble adding more than one intent-filter.

**Comment by dpa99c** [comment]
@rodneyweaver The problem is your parent XPath is incorrect: it should be `./application/activity/[@android:name='MainActivity']` not `application/activity/[@android:name='MainActivity']` - see the console output below for validation and the [config.xml of the example project](https://github.com/dpa99c/cordova-custom-config-example/blob/master/config.xml) for reference.

<details>
<summary>console output</summary>

```

$ cordova -v
7.0.1

$ cordova plugin ls
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-whitelist 1.3.2 "Whitelist"

$ cordova platform ls
Installed platforms:
  android 6.2.3
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0

$ more platforms/android/AndroidManifest.xml
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="uk.co.workingedge.phonegap.plugins.example.customconfig" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:maxSdkVersion="102" android:minSdkVersion="101" android:targetSdkVersion="103" />
</manifest>

$ more config.xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="uk.co.workingedge.phonegap.plugins.example.customconfig" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Custom config plugin example</name>
    <content src="index.html" />
    <access origin="*" />
    <preference name="Fullscreen" value="false" />
    <platform name="android">
        <config-file parent="./application/activity/[@android:name='MainActivity']" target="AndroidManifest.xml">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="ShareIntent" android:name="ShareIntent">
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="*/*" />
            </intent-filter>
            <intent-filter android:label="EmailIntent" android:name="EmailIntent">
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.BROWSABLE" />                
                <category android:name="android.intent.category.DEFAULT" />
                <data android:host="gmail-ls" />
                <data android:scheme="content" />
                <data android:mimeType="application/octet-stream" />
            </intent-filter>
        </config-file>
    </platform>
    <engine name="android" />
    <engine name="ios" />
    <plugin name="cordova-custom-config" spec="*" />
    <plugin name="cordova-plugin-whitelist" spec="1.0.0" />
</widget>

$ cordova prepare android
cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to D:\Git\cordova-custom-config-example\platforms\android\AndroidManifest.xml

$ more platforms/android/AndroidManifest.xml
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="uk.co.workingedge.phonegap.plugins.example.customconfig" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:label="ShareIntent" android:name="ShareIntent">
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="*/*" />
            </intent-filter>
            <intent-filter android:label="EmailIntent" android:name="EmailIntent">
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.BROWSABLE" />                
                <category android:name="android.intent.category.DEFAULT" />
                <data android:host="gmail-ls" />
                <data android:scheme="content" />
                <data android:mimeType="application/octet-stream" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:maxSdkVersion="102" android:minSdkVersion="101" android:targetSdkVersion="103" />
</manifest>

```

</details>

**Comment by rodneyweaver** [comment]
That solved it, thank you!
