### ISSUE TITLE
methods to understand remote cloud build system "config-file" logic

### ISSUE THREAD

**Issue by anetz89** [dpa99c/cordova-custom-config#122]
As already mentioned in the README, this plugin does not work with remote cloud build systems, like PhoneGap - which is OK as there is a workaround by putting both configs in the config.xml file.
But this is not as maintainable as it could be.

Here is the difference between the cordova-custom-config and the PhoneGap config config.xml:
```xml
<!-- PhoneGap -->
<gap:config-file platform="android" parent="/manifest" target="AndroidManifest.xml" mode="add">
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</gap:config-file>
```

```xml
<!-- cordova-custom-config -->
<platform name="android">
        <config-file parent="./" target="AndroidManifest.xml" mode="add">
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        </config-file>
</platform>
```
As there is not too much difference between the PhoneGap "config-file" and the cordova-custom-config I wonder if it is possible to add support for this kind of PhoneGap configuration.

The main differences in my eyes:
* platform wrapper-tag compared to platform-attribute
* different tag name ("gap:" prefix in PhoneGap config
* parent attribute starting with "./" instead of "/manifest" 

What do you think? Unfortunately I also don't have any experience with other remote build services, but I assume they work in a similar way.

**Comment by dpa99c** [comment]
I see the logic behind your request, so I'll add this to the TODO list, but I can't guarantee I'll get around to implementing it soon.

**Comment by anetz89** [comment]
thank you! no worries, maybe I find some time to create a pull request.

**Comment by dpa99c** [comment]
This is no longer relevant since cordova CLI (`@7/@8`) itself now parses `<config-file>` blocks hence this plugin has changed to use `<custom-config-file>` to avoid collision with cordova CLI.
