### ISSUE TITLE
Adding UIBackgroundModes fails

### ISSUE THREAD

**Issue by andersborgabiro** [dpa99c/cordova-custom-config#124]
When I unzip the IPA file, there's no setting of UIBackgroundModes, only NSLocationXxx. Any idea?

```
    <config-file platform="ios" target="*-Info.plist" parent="UIBackgroundModes">
        <array>
            <string>location</string>
        </array>
    </config-file>

    <config-file platform="ios" target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
        <string>This app requires constant access to your location in order to track your position, even when the screen is off.</string>
    </config-file>

    <config-file platform="ios" target="*-Info.plist" parent="NSLocationWhenInUseUsageDescription">
        <string>This app will now only track your location when the screen is on and the app is displayed.</string>
    </config-file>
```

**Comment by dpa99c** [comment]
After running `cordova prepare ios`, do you see the key in the iOS project `.plist`? Any when you open the project in Xcode, do you see Background Location is checked under Capabilities?

**Comment by andersborgabiro** [comment]
I don't use CLI, but rather PhoneGap Build, so I can only see what's in the IPA.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-custom-config#important-note-for-remote-build-environments):

> This plugin **WILL NOT WORK** with remote ("Cloud") build environments that do not support the execution of this plugin's [hook scripts](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/). This includes:
>- [Phonegap Build](https://github.com/phonegap/build/issues/425) 
>- [Intel XDK](https://software.intel.com/en-us/xdk/docs/add-manage-project-plugins)
>- [Telerik Appbuilder](http://docs.telerik.com/platform/appbuilder/cordova/using-plugins/using-custom-plugins/using-custom-plugins)
>- [Ionic Cloud](https://docs.ionic.io/services/package/#hooks)
