### ISSUE TITLE
updateIosPbxProj - parseSync

### ISSUE THREAD

**Issue by EDumdum** [dpa99c/cordova-custom-config#125]
Hi,

We are using your plugin with other plugins.
These others plugin parse/writte synchronously the pbxproj in the after_prepare phase too.
But, sometimes, the result is overwritten. We identified that it may be due to the fact that in function updateIosPbxProj you are parsing (then writting) asynchronously the same file as us.

Is it possible to switch to synchronous parsing/writting?

We can make a fork/pull request if needed.

Regards,
Etienne

**Comment by chrisie** [comment]
@EDumdum Just out of curiosity, which version of the plugin are you using? We had the same problem in versions prior to 3.1.3 but 3.1.3 fixed it (from what I can tell it just synchronises the update "manually" through the checkComplete method rather than using synchronous parsing / writing).

**Comment by dpa99c** [comment]
@EDumdum As @chrisie says, this should have been fixed by commit 74b43fe6dd4e93abc90d0a025bc5976088d4fbc4.  Please confirm which plugin version you are using.

**Comment by dpa99c** [comment]
Closed due to no response from OP

**Comment by EDumdum** [comment]
Hi,

Sorry for the late response, I was not available.
We were still using 3.0.14.
Works perfectly with version 3.1.3.

Thanks!
