### ISSUE TITLE
Preference VALID_ARCHS fails to add as string and corrupts project file 

### ISSUE THREAD

**Issue by GitRubb** [dpa99c/cordova-custom-config#13]
When using the following preference:

name="ios-XCBuildConfiguration-VALID_ARCHS" value="arm64 armv7"

The result in project.pbxproj is
VALID_ARCHS = arm64 armv7;
expected result is
VALID_ARCHS = "arm64 armv7";

**Comment by dpa99c** [comment]
There's a fix for this in v1.1.5, which now escapes values inserted into the .pbxproj. I just published to npm, so update the plugin to v1.1.5 and it should resolve the issue.

**Comment by GitRubb** [comment]
Thanks so much and for the quick response! 

One quick question if you have time, I would like to auto add a Run Script in the Build Phases. Does this plugin have the ability to create a new script? Once that's added I believe it should be able to handle the rest as follows

preference name="ios-PBXShellScriptBuildPhase-shellPath" value="/usr/bin/python"
preference name="ios-PBXShellScriptBuildPhase-shellScript" value="python script here"

**Comment by dpa99c** [comment]
The plugin can't add scripts/source files/frameworks yet, but the underlying [xcode](https://www.npmjs.com/package/xcode) module supports those operations. When I get time, I intend to expose much more of its functionality.

**Comment by dpa99c** [comment]
Adding of scripts added to [TODO list](https://github.com/dpa99c/cordova-custom-config/wiki/TODO), so closing this as escaping issue is resolved
