### ISSUE TITLE
Create a <project_name>.entitlements file possible?

### ISSUE THREAD

**Issue by TanjaBieber** [dpa99c/cordova-custom-config#131]
Hi, 
is it possible to create or overwrite a <project_name>.entitlements file for iOS with this plugin?
If yes, which entries in the config.xml file do i need?
PS: Using version 3.2.0 of this plugin. Working with an VS 15 and a remote compiler for iOS.

**Comment by dpa99c** [comment]
The plugin will currently enable you to modify (not create) an existing entitlements file.

Specify the filename in a [`<config-file>`](https://github.com/dpa99c/cordova-custom-config#ios-project-plist-config-blocks) block, for example:

    <config-file platform="ios" target="Entitlements-Release.plist" parent="aps-environment" mode="replace">
      <string>production</string>
    </config-file>
    
    <config-file platform="ios" target="Entitlements-Debug.plist" parent="aps-environment" mode="replace">
      <string>development</string>
    </config-file>

**Comment by dpa99c** [comment]
Note that in a `cordova-ios` project, `Entitlements-Release.plist` and `Entitlements-Debug.plist` should be created by Cordova

**Comment by TanjaBieber** [comment]
I need to set the com.apple.developer.default-data-protection value in my application to a higher level. As far as I know, this must be set in the *.entitlements file and not in the Entitlements-*.plist files. So is it possible to set this option with your plugin?

**Comment by dpa99c** [comment]
You can do it in the `Entitlements-*.plist` ([see here](https://stackoverflow.com/a/15772475/777265)), for example:

    <config-file platform="ios" target="Entitlements-Release.plist" parent="com.apple.developer.default-data-protection" mode="add">
        <string>NSFileProtectionComplete</string>
    </config-file>

**Comment by joaoduartemariucio** [comment]
Does this solution still work?
