### ISSUE TITLE
Error updating config for platform 'ios': Unexpected key "NSContactsUsageDescription" while parsing <dict/>.

### ISSUE THREAD

**Issue by tobiasmuecksch** [dpa99c/cordova-custom-config#132]
Hey there,

I'm currently experiencing the following error, when I try to add the iOS platform.

```
cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to /Users/tmuecksch/Sites/myApp/platforms/ios/myApp/myApp-Info.plist
cordova-custom-config: Error updating config for platform 'ios': Unexpected key "NSContactsUsageDescription" while parsing <dict/>.
```

When I look at the `myApp-Info.plist` the file seems correctly assembled to me. But the build process doesn't finish correctly after this error message.
```
[ ... ]
        </dict>
      </dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
    <key>UILaunchStoryboardName</key>
    <string>CDVLaunchScreen</string>
    <key>NSContactsUsageDescription</key>
    <string>displaying and syncing contacts</string>
  </dict>
</plist>
```

*Versions*
- Cordova Platforms  : ios 4.5.4
- Plugins: 
    - cordova-custom-config 4.0.2 "cordova-custom-config"
    - cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
    - cordova-plugin-device 1.1.4 "Device"
    - cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
    - cordova-plugin-splashscreen 4.0.3 "Splashscreen"
    - cordova-plugin-whitelist 1.3.1 "Whitelist"
    - ionic-plugin-keyboard 2.2.1 "Keyboard"

Since this error message is not helpful - **what can I do to debug that error further?**

**Comment by dpa99c** [comment]
The error message is arising from the [plist module](https://www.npmjs.com/package/plist) when attempting to [rebuild the plist contents](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L671).

Please post the `<config-file>` block corresponding to the reported error key - without seeing it, it's not possible to diagnose the issue.

**Comment by tobiasmuecksch** [comment]
Ah, shoot. I forgot to add that. Thanks for the reminder.

The `[...]` means that I've removed code to make the xml code shorter.  In case you need the full code let me know.

There you go:

```
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
[...]
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" 
[...]
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <config-file parent="NSContactsUsageDescription" target="*-Info.plist">
            <key>NSContactsUsageDescription</key>
            <string>displaying and syncing contacts</string>
        </config-file>
    </platform>
```

**Comment by tobiasmuecksch** [comment]
I've tried it without the parent attribute too, like this:
```
    <config-file parent="NSContactsUsageDescription" target="*-Info.plist">
            <key>NSContactsUsageDescription</key>
            <string>displaying and syncing contacts</string>
        </config-file>
```

But still the same error.

**Comment by dpa99c** [comment]
Specifying the `<key>` is causing the problem since it's already been defined by the `parent` attribute.
The `platform="ios"` attribute is also necessary for `<config-file>` blocks.

    <config-file platform="ios" parent="NSContactsUsageDescription" target="*-Info.plist">
        <string>displaying and syncing contacts</string>
    </config-file>

You may to need to re-add the iOS platform to start with a fresh `*-Info.plist`:

    cordova rm platform ios --nosave && cordova platform add ios --nosave

**Comment by tobiasmuecksch** [comment]
That did the trick. Thank you so much!
