### ISSUE TITLE
Ionic 3.19 plugin wrapper breaks plugin install

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-custom-config#140]
Hey Dave...busy weekend with a lot of your plugins.  :-)  Going full tilt upgrade here!  LOL.  

Just an FYI:

With `ionic` wrapper:
**ionic cordova plugin add cordova-custom-config --save
> cordova plugin add cordova-custom-config --save
(node:9972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin cordova-custom-config via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rolin\AppData\Roaming\npm-cache\_logs\2018-02-17T20_50_59_059Z-debug.log:**

Without `ionic` wrapper:
**cordova plugin add cordova-custom-config --save
Installing "cordova-custom-config" for android
Android Studio project detected
Adding cordova-custom-config to package.json
Saved plugin info for "cordova-custom-config" to config.xml**

...and it compiled and deployed successfully.

**Comment by dpa99c** [comment]
The git submodule stuff is entirely unrelated to this plugin, therefore must be an issue with the Ionic CLI. This is verified by the fact it works fine with the Cordova CLI. Best thing is to open an issue against the Ionic CLI because I don't think I can do anything from the code within this plugin to fix it.
