### ISSUE TITLE
where my custom MainActivity can be located

### ISSUE THREAD

**Issue by lizhen0211** [dpa99c/cordova-custom-config#142]
where my custom MainActivity can be located
For example, PhotoGpsActivity is in AndroidManifest.xml，but where can I impliment it

**Comment by dpa99c** [comment]
This plugin's sole purpose is to enable you to define custom configuration. For example, if you include a plugin which contains an SDK that requires a custom `<activity>` definition in the manifest, you can use this plugin to do so.

However, if you are wanting to implement custom code, as well as configuration, for example to both define and implement an activity called `PhotoGpsActivity`, then you'd need to create your own [Cordova plugin](https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html) and in which case you'd include your activity manifest entry in a `<config-file>` block within the `plugin.xml`.

**Comment by lizhen0211** [comment]
Thanks your help
