### ISSUE TITLE
android platform 7.1.1 + cordova 8.1.0 - cordova-custom-config: Error loading dependencies for applyCustomConfig.js

### ISSUE THREAD

**Issue by Muzietto** [dpa99c/cordova-custom-config#149]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

I am upgrading my environment to move beyond cordova 6.x.x.

During an "cordova platform add android --fetch" the execution stops  with:

    CordovaError: Promise rejected with non-error: 'cordova-custom-config: Error loading dependencies 
    for applyCustomConfig.js - ensure the plugin has been installed via cordova-fetch or run \'npm 
    install cordova-custom-config\': Cannot find module \'elementtree\''
    at cli.catch.err (/home/marco/workspace/eidoo-app/node_modules/cordova/bin/cordova:29:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    [15:04:29] 'prepare-cordova' errored after 11 min

The error message clearly states that the issue happens during the run of cordova-custom-config. However I am already running everything with `--fetch`

I have modified the config.xml file according to https://www.npmjs.com/package/cordova-custom-config#changes-in-cordova-custom-config5

**Expected behavior:**

The `cordova platform add android` command runs without interruption.

**Environment information**

- Cordova CLI version 
	- `cordova -v` --> 8.1.0
- Cordova platform version
	- `cordova platform ls` --> android 7.1.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls` 

	cordova-clipboard 1.2.1 "Clipboard"
	cordova-custom-config 5.0.2 "cordova-custom-config"
	cordova-plugin-android-fingerprint-auth 1.4.4 "FingerprintAuth"
	cordova-plugin-appavailability 0.4.2 "AppAvailability"
	cordova-plugin-camera 4.0.3 "Camera"
	cordova-plugin-device 1.1.4 "Device"
	cordova-plugin-globalization 1.11.0 "Globalization"
	cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
	cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
	cordova-plugin-prevent-screenshot 1.0.0 "BlockScreenShot"
	cordova-plugin-root-detection 0.1.1 "Root Detection"
	cordova-plugin-splashscreen 5.0.2 "Splashscreen"
	cordova-plugin-statusbar 2.4.2 "StatusBar"
	cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
	cordova-plugin-wkwebview-inputfocusfix 1.0.1 "WKWebView Input Focus Fix"
	cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
	es6-promise-plugin 4.1.0 "Promise"
	onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
	phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"

- Dev machine OS and version, e.g.
    - Linux Ubuntu 16.04

**Comment by Muzietto** [comment]
Same error on MacOS 10.14. Please comment!

**Comment by dpa99c** [comment]
This is not happening for me in a test case - see console output below.

If possible, please provide a similar set of reproducible steps which recreates the issue.


<details>
<summary>console output</summary>

```

$ cordova -v
8.1.0

$ node -v
v9.2.1

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

$ npm -v
5.6.0

$ cordova create test && cd test
Creating a new cordova project.

$ cordova plugin add cordova-custom-config
Adding cordova-custom-config to package.json
Saved plugin info for "cordova-custom-config" to config.xml

$ cordova platform add android
Using cordova-fetch for cordova-android@~7.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Installing "cordova-custom-config" for android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~7.1.1 into config.xml file ...

$ cordova prepare android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Android Studio project detected

$ cordova platform rm android
Removing platform android from config.xml file...
Removing android from cordova.platforms array in package.json

$ rm -Rf node_modules/

$ cordova platform add android
Using cordova-fetch for cordova-android@~7.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Installing "cordova-custom-config" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
cordova-custom-config: Skipping auto-restore of config file backup(s)
--save flag or autosave detected
Saving android@~7.1.1 into config.xml file ...

$ cordova prepare android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Android Studio project detected

$ rm -Rf plugins/ node_modules/ platforms/

$ cordova platform add android
Using cordova-fetch for cordova-android@^7.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-custom-config" in config.xml. Adding it to the project
Installing "cordova-custom-config" for android
Adding cordova-custom-config to package.json
Saved plugin info for "cordova-custom-config" to config.xml
--save flag or autosave detected
Saving android@~7.1.1 into config.xml file ...

$ cordova prepare android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Android Studio project detected

```

</details>

**Comment by Muzietto** [comment]
Done some more experimentation. I am actually able to run the computation further by installing manually npm packages.

So far I've installed:

- elementtree
- xcode
- simple-plist
- bplist-parser
- big-integer

I see some of them are explicitly mentioned inside applyCustomConfig.js; others could be dependencies of the earlier ones. Any idea?

**Comment by dpa99c** [comment]
Some of these are [direct dependencies of this plugin](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L33) and others I would assume are sub-dependencies or dependencies of other plugins.
Using `cordova@7` or above, the dependencies of this plugin should be satisfied by Cordova via npm.

Seems like something is going wrong with that dependency resolution or with your local `node_modules`.
You could try to reproduce it in an isolated test project to rule out conflicts with other plugins.

**Comment by dpa99c** [comment]
Closed due to no response from OP

**Comment by sirius2013** [comment]
![image](https://user-images.githubusercontent.com/5020713/47420079-451e4000-d786-11e8-8335-9e0066683743.png)
@dpa99c  I got same error now.

**Comment by marcus13371337** [comment]
Same error!

**Comment by expcapitaldev** [comment]
have the same issue
check if cordova-custom-config is added in package.json in dependencies node
