### ISSUE TITLE
feat: update plist depency tonpm repository

### ISSUE THREAD

**Issue by ggggr** [dpa99c/cordova-custom-config#151]
Hi,

this is a really nice & useful plugin.
However, is it possible to change the plist dependcy from "plist": "xiangpingmeng/plist.js" to "plist": "^3.0.1".

It will be resolve directy without doing a ssh to the github repo xiangpingmeng/plist.js.

Thanks,

**Comment by dpa99c** [comment]
Looks like https://github.com/TooTallNate/plist.js/pull/84 fixed this, so I'll switch back to `plist@3.0.1` and push out a patch release.

**Comment by dpa99c** [comment]
Published in `cordova-custom-config@5.0.3`
