### ISSUE TITLE
The prefix "ns1" for attribute "ns1:name" associated with an element type "meta-data" is not bound

### ISSUE THREAD

**Issue by rhanesoghlyan** [dpa99c/cordova-custom-config#153]
For configuring push notification icon in my Ionic project I did some changes in config.xml file. 
But I've got a error. 

> The prefix "ns1" for attribute "ns1:name" associated with an element type "meta-data" is not bound.

This is my widget
`<widget id="test" version="0.0.3" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">`

And my config file tags:
`<hook src="package-hooks/android_custom_resources.js" type="after_prepare" />
    <hook src="package-hooks/android_custom_values.js" type="after_prepare" />
    <config-file parent="./application" target="AndroidManifest.xml">
      <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
      <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/red" />
    </config-file>`

**Comment by dpa99c** [comment]
You are using the `<config-file>` element which will be parsed by Cordova. 
If you wish to make use of this plugin, you need to use [`<custom-config-file>`](https://github.com/dpa99c/cordova-custom-config#android-config-blocks).

Please see the [example project](https://github.com/dpa99c/cordova-custom-config-example) as reference for a working example.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by rhanesoghlyan** [comment]
Sorry for the late response. But I've tried with <custom-config-file> as well. The same result

**Comment by dpa99c** [comment]
Have you tried the [example project](https://github.com/dpa99c/cordova-custom-config-example)? It's a known working environment you can use for comparison with your own project. Try it as is, then try adding your own config blocks to it and see what happens.

**Comment by rhanesoghlyan** [comment]
@dpa99c thanks a lot. Will try. I'll come back with updates
