### ISSUE TITLE
Cordova builds fail with XCode-beta 11

### ISSUE THREAD

**Issue by AnthonySmith01** [dpa99c/cordova-custom-config#161]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

Using XCode-beta 11 causes Cordova to throw the following build error from the CLI
cordova-custom-config: Applied custom config from config.xml to /App/platforms/ios/App/App-Info.plist
Reading build config file:
Cannot read property 'toLowerCase' of undefined

The bug appears when using the Cordova build command on a Mac running XCode-beta 11. Run cordova build ios from the command line with the plugin installed.

The error message above is closely related to the plugin.

**Expected behavior:**

The Cordova build process should complete without throwing errors

**Comment by AnthonySmith01** [comment]
Seems to be resolved after updating to new plugin.

**Comment by AnthonySmith01** [comment]
Closed a bit too soon, unfortunately the issue re-emerged.

This is using cordova-custom-config 5.1.0.

**Comment by dpa99c** [comment]
Interesting - I haven't had chance to download Xcode 11 Beta yet and try it out (since it's only been out a few hours). Does a vanilla `cordova-ios` project (without this plugin) build OK in Xcode 11 Beta?

**Comment by AnthonySmith01** [comment]
Ahh thanks for the pointer, I was positive this was the custom config plugin.

I'm running Cordova 8.1.2 still, it looks like this problem is in Cordova itself. I'll try the newer version and raise an issue in the cordova-ios repo.
