### ISSUE TITLE
Question: is this plugin needed for UISupportedInterfaceOrientations?

### ISSUE THREAD

**Issue by l3ender** [dpa99c/cordova-custom-config#166]
I'm having trouble determining if this plugin is needed for configuring `UISupportedInterfaceOrientations` and `UISupportedInterfaceOrientations~ipad` and am wondering if someone could provide guidance.

It seems like the customization for orientations should be supported with [edit-config](https://cordova.apache.org/docs/en/latest/config_ref/index.html#edit-config) or [config-file](https://cordova.apache.org/docs/en/latest/config_ref/index.html#config-file) options in `config.xml` file, but I haven't had any luck. Additionally, we have a custom Cordova plugin where I've tried the same and I am not seeing my customizations reflected in the final plist file.

```
-> cordova -v
9.0.0 (cordova-lib@9.0.1)
```

I've tried the following in both `config.xml` and our custom plugin's `plugin.xml`:

```xml
<config-file target="*-Info.plist" parent="UISupportedInterfaceOrientations">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</config-file>
<config-file target="*-Info.plist" parent="UISupportedInterfaceOrientations~ipad">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</config-file>
```
and
```xml
<edit-config file="*-Info.plist" mode="overwrite" target="UISupportedInterfaceOrientations">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</edit-config>
<edit-config file="*-Info.plist" mode="overwrite" target="UISupportedInterfaceOrientations~ipad">
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</edit-config>
```

So I wanted to see if this plugin is required for the above configuration, or if can be successfully accomplished with core/base Cordova configuration.

Many thanks!

**Comment by dpa99c** [comment]
You should be able to use `<config-file>` blocks to specify custom orientation settings and Cordova will pick up and apply those. Be sure not to specify `<preference name="Orientation" /> in your `config.xml` as this will take precedence.
If you encounter issues, you can use this plugin to apply a `<custom-config-file>` block.

**Comment by l3ender** [comment]
Did some more research, and editing `array` plist entries (like `UISupportedInterfaceOrientations`) is not currently supported by Cordova. See https://github.com/apache/cordova-ios/issues/613.
