### ISSUE TITLE
Config.xml Bug

### ISSUE THREAD

**Issue by javico-dev11** [dpa99c/cordova-custom-config#177]
I am adding android:exported in AndroidManifest.xml but the edited service or activity is duplicated

`<activity android:launchMode="singleTop" android:name="com.gae.scaffolder.plugin.FCMPluginActivity">
            <intent-filter>
                <action android:name="FCM_PLUGIN_ACTIVITY" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
`

For example if I add android:exported it duplicates that code without the added attribute

**Comment by sarathi0333** [comment]
@javico-dev11 Have you found a solution? i'm trying to create Android12 support for our app. I too face the same issue when I add `android:exported`

When we execute `"Cordova platform add android"` it adds the config, then if we execute `Cordova prepare android` it creates duplicate.

**Comment by sarathi0333** [comment]
I just added the below line in _`Config.xml`_ and it worked for me.
`<preference name="cordova-custom-config-autorestore" value="true" />`

**Comment by rondog** [comment]
@sarathi0333 what did your line look like in the config.xml for adding that `android:exported` value? I am trying to do the same thing, however, its adding the line to the <application> tag.

Currently using this but its wrong

`<custom-preference name="android-manifest/application/service[@android:name='org.apache.cordova.firebase.FirebasePluginMessagingService']" value="@android:exported/false" /> `

**Comment by rondog** [comment]
I ended up doing this. I think that is what I wanted. I was confused by the docs

```
        <custom-config-file target="AndroidManifest.xml" parent="./application">
          <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService" android:exported="false">
            <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
          </service>
        </custom-config-file>
```

**Comment by rondog** [comment]
apparently when I run build through the ionic dashboard, this does not work.

**Comment by tohhierallie** [comment]
Hey Guys,

So this worked for me. I found that the following runs after the firebase plugin edits the manifest. Which means we can delete and add a new service or merge which ever works for you. 

```
<custom-preference delete="true" name="android-manifest/application/service[@android:name='org.apache.cordova.firebase.FirebasePluginMessagingService']" /> 

<custom-config-file mode="merge" parent="./" target="AndroidManifest.xml"> 
    <service android:enabled="true" android:exported="false" android:name="org.apache.cordova.firebase.FirebasePluginMessagingService"> 
        <intent-filter> 
            <action android:name="com.google.firebase.MESSAGING_EVENT" /> 
        </intent-filter> 
    </service> 
</custom-config-file>
```
