### ISSUE TITLE
Optimize hook names for setup and removal

### ISSUE THREAD

**Issue by regnete** [dpa99c/cordova-custom-config#2]
Hi Dave,

what about using the special hooknames 'before_plugin_install' and 'before_plugin_uninstall' for setup/removal of your plugin? (see http://cordova.apache.org/docs/en/5.1.1/guide/appdev/hooks/)

Currently you are using 'before_plugin_rm' and 'after_plugin_add'. These will fire each time **any** plugin is added/removed.

The hooks names mentioned above should only fire, when **your** plugin is added or removed. This could have massive perfomance impacts on your users cordova build process.

**Comment by dpa99c** [comment]
Thanks for clarifying these - didn't realize  'before_plugin_rm' and 'after_plugin_add' fired on _any_ plugin - the docs are not very clear on this. I'll swap these to 'before_plugin_install' and 'before_plugin_uninstall' when I get a bit of time.
