### ISSUE TITLE
Error : cordova-custom-config: Error updating config for platform 'android': undefined is not a function

### ISSUE THREAD

**Issue by ms3eed** [dpa99c/cordova-custom-config#21]
Using your example project 
While trying to run ``` cordova prepare android --verbose``` I always get the below error

My Cordova veriosn 5.0.0

>TypeError: undefined is not a function
>    at getConfigFilesByTargetAndParent (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:100:19)
>   at parseConfigFiles (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:201:27)
>    at parseConfigXml (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:114:9)
>    at updatePlatformConfig (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:431:26)
>    at /home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:486:17
>    at arrayEach (/home/mostafa/node_modules/lodash/lodash.js:446:11)
>   at Function.forEach (/home/mostafa/node_modules/lodash/lodash.js:7482:11)
>    at applyCustomConfig.init (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/applyCustomConfig.js:483:11)
>    at /home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/resolveDependencies.js:46:11
>    at installRequiredNodeModules (/home/mostafa/workspace/cordova-custom-config-example/plugins/cordova-custom-config/hooks/resolveDependencies.js:109:7)

May you help on that?

**Comment by dpa99c** [comment]
Cause is the backwardly-incompatible update released to lodash library yesterday - see #20.
Will fix when I get some time as fix is non-trivial.

**Comment by ms3eed** [comment]
Thanks  Dave

**Comment by dpa99c** [comment]
Fixed by 9e8971266c6dffe67a6e21dda21fc5e60afd318b
