### ISSUE TITLE
Adding the plugin before 'cordova platform add' will give 'cannot find module ...' errors

### ISSUE THREAD

**Issue by NickAdriaenssens** [dpa99c/cordova-custom-config#23]
2 error examples I got:
```
Error: Cannot find module 'tostr'
Error: Cannot find module 'elementtree'
```

The plugin works fine if I add the plugin after ```cordova platform add```
Is this necessary or is there something else wrong?

**Comment by dpa99c** [comment]
Seems that the `after_plugin_install` hook, which the plugin uses to execute its dependency resolution script, does not run if the plugin is added to a project before a platform is added. I've updated the plugin to also run the dependency resolution script on `after_platform_add` hook.  v1.1.11 of the plugin is now on the git master branch and also published to npm. This resolved the issue for me - please can you confirm it does the trick for you?

**Comment by NickAdriaenssens** [comment]
I tried 1.1.11 but it did not seem to work. I currently have not enough time to go any deeper on this issue, but I will get on it whenever I can.

**Comment by NickAdriaenssens** [comment]
I can confirm It's working now. Thanks a lot!
