### ISSUE TITLE
Error parsing XML: unbound prefix when doing cordova build android

### ISSUE THREAD

**Issue by Joustie** [dpa99c/cordova-custom-config#24]
Hi,
Thanks for making this plugin. I really need this functionality. Unfortunately it breaks my cordova android build with this error:
`../platforms/android/build/intermediates/res/armv7/debug/xml/config.xml:43: error: Error parsing XML: unbound prefix`

That line says:
`<config-file parent="/*" target="AndroidManifest.xml">
        <uses-permission android:name="android.permission.CAMERA" />
    </config-file>`

The root config.xml file used by this installation has the following config platform settings that are used by your plugin:
`<platform name="android">
      <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.CAMERA" />
      </config-file>
        <preference name="android-manifest/application/@android:name" value="com.joustie.foo.App" />
        <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
        <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
        <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
        <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
        <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
        <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
        <splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
        <splash src="resources/android/splash/drawable-land-mdpi-screen.png" density="land-mdpi"/>
        <splash src="resources/android/splash/drawable-land-hdpi-screen.png" density="land-hdpi"/>
        <splash src="resources/android/splash/drawable-land-xhdpi-screen.png" density="land-xhdpi"/>
        <splash src="resources/android/splash/drawable-land-xxhdpi-screen.png" density="land-xxhdpi"/>
        <splash src="resources/android/splash/drawable-land-xxxhdpi-screen.png" density="land-xxxhdpi"/>
        <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
        <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
        <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
        <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
        <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
        <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
    </platform>`

Any idea why android build fails? The  AndroidManifest.xml file int he platform directory is correctly updated by your plugin code, but it seems to also alter an 'intermediate' file that is parsed in the android build phase?

**Comment by SvenTobback** [comment]
Hi Joustie,

Did you add the Android namespace to the config.xml? 

The ````xmlns:android="http://schemas.android.com/apk/res/android"```` attribute should be added to the root ````<widget>```` tag inside the config.xml if you want to use ````<tag android:abc>````.

Hope this helps.

**Comment by Joustie** [comment]
Hi,

That was it. Thank you very much!

Regards,
Joost

Op dinsdag 19 januari 2016 heeft SvenTobback <notifications@github.com> het
volgende geschreven:

> Hi Joustie,
>
> Did you add the Android namespace to the config.xml?
>
> The xmlns:android="http://schemas.android.com/apk/res/android" attribute
> should be added to the root <widget> tag inside the config.xml if you
> want to use <tag android:abc>.
>
> Hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpa99c/cordova-custom-config/issues/24#issuecomment-172981002>
> .
>


-- 
Joost Evertse
Private email: joustie@gmail.com
Web: http://www.joustie.nl
Twitter: joustie
Hyves: http://joustie.hyves.nl
Facebook: http://www.facebook.com/profile.php?id=1402911295&ref=name

**Comment by dpa99c** [comment]
Glad you got it sorted - I'll update the plugin documentation to state that this namespace needs to be included in config.xml

**Comment by Edison4mobile** [comment]
@SvenTobback 
you are best.

**Comment by rhanesoghlyan** [comment]
@SvenTobback I've got this error message when building project in Android platform.

> The prefix "ns1" for attribute "ns1:name" associated with an element type "meta-data" is not bound.

This is my widget
`<widget id="test" version="0.0.3" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">`

And my config file tag:
`<hook src="package-hooks/android_custom_resources.js" type="after_prepare" />
    <hook src="package-hooks/android_custom_values.js" type="after_prepare" />
    <config-file parent="./application" target="AndroidManifest.xml">
      <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
      <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/red" />
    </config-file>`

**Comment by distinctdan** [comment]
Is there a way to programmatically set it on the widget? Editing anything in the build process by hand seems like it would defeat the whole point of this plugin.

**Comment by distinctdan** [comment]
I've tried manually adding it, but it gets overwritten when cordova prepares. Not sure what to do here.

**Comment by distinctdan** [comment]
Got it figured out, I didn't realize this was talking about the main `cordova/config.xml` file, not the one in the platforms folder that was throwing the error.

**Comment by darrensapalo** [comment]
Thanks to @distinctdan for giving me an idea of where I'm going wrong with how I was solving this same problem of mine. 

For `ionic-v3` users building on the Android platform, I detailed exactly which config.xml file to edit  in your project folder [on this ionic forum post](https://forum.ionicframework.com/t/config-file-working-on-android-builds-for-anyone/73291/5?u=darrensapalo).

**Comment by gsingh0101** [comment]
> Hi Joustie,
> 
> Did you add the Android namespace to the config.xml?
> 
> The `xmlns:android="http://schemas.android.com/apk/res/android"` attribute should be added to the root `<widget>` tag inside the config.xml if you want to use `<tag android:abc>`.
> 
> Hope this helps.

It worked, thanks

**Comment by sreenumalae** [comment]
> Hi Joustie,
> 
> Did you add the Android namespace to the config.xml?
> 
> The `xmlns:android="http://schemas.android.com/apk/res/android"` attribute should be added to the root `<widget>` tag inside the config.xml if you want to use `<tag android:abc>`.
> 
> Hope this helps.

Hi @SvenTobback 
I have similar error. Clearly mention in the below link
https://forum.ionicframework.com/t/error-while-building-release-apk/176575/7
I'm getting error while I'm trying to build release apk (Cordova build android --release)
please help me out.

**Comment by ssnielsen** [comment]
@rhanesoghlyan This might be a long shot, but here goes... I'm running into the same problem as you - did you ever find a viable solution?

**Comment by l3ender** [comment]
I ran into this issue when using `edit-config` in config.xml. As the file is copied to app/src/main/res/xml/config.xml, it also is processed during compilation. Therefore I needed to add the same namespace to the `widget` element in config.xml:

```xml
<widget ...
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:cdv="http://cordova.apache.org/ns/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android">
```
