### ISSUE TITLE
Plugin breaking Android and iOS version codes

### ISSUE THREAD

**Issue by bostondv** [dpa99c/cordova-custom-config#25]
When the plugin is installed, Android version code and iOS bundle version are not updated in the platforms from their values in config.xml

Widget element looks like this:

`<widget android-versionCode="28" id="com.app.my" ios-CFBundleVersion="28" version="3.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">`

With the plugin removed, values update correctly.

**Comment by dpa99c** [comment]
Short answer - add this to your config.xml:

    <preference name="cordova-custom-config-autorestore" value="false" />

Long answer: this is being caused as a side effect of the [backup behaviour](https://github.com/dpa99c/cordova-custom-config#backups) which is turned on by default in the plugin (I may have to reconsider this). The plugin attempts to make custom config settings "removable" by taking a backup of the platform config files before the first `prepare` operation after the plugin is installed. In theory this should restore the original platform config file, allowing this plugin and cordova to modify it to produce an up-to-date version. Without this behaviour, if a custom config setting defined in the config.xml is applied to a platform config file, then removed from the config.xml, there's no (easy) way to remove the corresponding config setting from the platform config file. The backup script is invoked as a [`before_prepare` hook](https://github.com/dpa99c/cordova-custom-config/blob/master/plugin.xml#L22), but it seems that cordova updates the version numbers in the platform config files even before the `before_plugin` hook scripts are executed, hence any updates made by cordova to version numbers are being overwritten when the backup platform config file is restored. Unfortunately there's not a `before_before_prepare` hook to restore the backups before cordova updates the version numbers, so for now the simple solution, as I've said above, is to turn off the auto-restore of backup files. Of course, this will have the side effect that any custom config values you remove from your config.xml will __not__ be removed from the corresponding platform files, so you'll need to do this manually.

**Comment by bostondv** [comment]
Awesome, that did the trick.

For my case I'm totally satisfied without the backup behaviour and I think
it may make sense to default it to off. Although it's handy, it's easy
enough to remove manually a value one time from the platform file.

Thanks!
