### ISSUE TITLE
Quote attribute on ios-XCBuildConfiguration preference tag is not documented in readme

### ISSUE THREAD

**Issue by erichochhalter** [dpa99c/cordova-custom-config#26]
The `quote` attribute which allows a user to configure in the `ios-XCBuildConfiguration` preference tag how xcconfig lines get rendered (introduced in 604703087231bd02d195daf04c2c98af132c12f9) is very useful, but I was unaware of its existence until I read the commit history and the source code. 
I recommend you add documentation and an example of this attribute to the readme.

**Comment by dpa99c** [comment]
Yes, sorry, thought I'd documented this, but apparently not. Added to the todo list...

**Comment by dpa99c** [comment]
Documentation added in 9f67f85a8048a239e4f96c0ea71b70e817ba1319
