### ISSUE TITLE
duplicated entry in generated AndroidManifest.xml

### ISSUE THREAD

**Issue by gitawego** [dpa99c/cordova-custom-config#34]
with this config:
```
<config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-feature android:name="android.hardware.camera" />
            <uses-feature android:name="android.hardware.camera.autofocus" />
        </config-file>
```
generated file AndroidManifest.xml contains twice ``android.hardware.camera.autofocus`` but not ``android.hardware.camera``

**Comment by dpa99c** [comment]
I'll have a look at this and get back to you...

**Comment by dpa99c** [comment]
Fix is pushed to master. Not released to npm yet as I have another couple of fixes to do, but you can install fixed version directly:

    cordova plugin add https://github.com/dpa99c/cordova-custom-config
