### ISSUE TITLE
Not working with Cordova 5.0.0?

### ISSUE THREAD

**Issue by mirko77** [dpa99c/cordova-custom-config#35]
Hi there, I am probably missing something silly, but it does not appear to work for me.

I want to change the AndroidManifest.xml so in my config.xml file I added your Android example xml, and I set the namespace correctly in my widget element.

Nothing changes in the manifest after I run cordova prepare. Looking at the log, `Running applyCustomConfig.js` is never called.

I tested your example and it works, same machine, same Cordova CLI and same android platform...

**Comment by dpa99c** [comment]
Can you try running `cordova prepare android --verbose` and post the output here?

Also check you're using the latest version (1.2.4) as I've made significant changes recently.

**Comment by mirko77** [comment]
Now it is working properly, go figure.
