### ISSUE TITLE
iOS config-file entries not appearing in *-Info.plist

### ISSUE THREAD

**Issue by johnkcox** [dpa99c/cordova-custom-config#36]
Using version 1.2.4 with cordova-ios@4.0.1. Have added a few config-file entries to try and add/overwrite entries in our *-Info.plist file and they are not appearing. We even tried just using one of your examples. Here's the output on the console during `$cordova prepare ios --verbose`:
```
cordova-custom-config: Write to plist; key=NSLocationAlwaysUsageDescription; value='This app requires constant access to your location in order to track your position, even when the screen is off.'
```
However, when you look at the plist file you see that the entry was not added.

**Comment by dpa99c** [comment]
I can't reproduce the behaviour you're observing with the [example project](https://github.com/dpa99c/cordova-custom-config-example) on iOS. Could you clone the example project repo and see if you observe the problem there too?

Here's the output from my Mac console:

    Daves-Mac:cordova-custom-config-example dave$ cordova -v
    6.0.0
    Daves-Mac:cordova-custom-config-example dave$ cordova platform ls
    Installed platforms: android 5.1.0, ios 4.0.1
    Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos
    Daves-Mac:cordova-custom-config-example dave$ cordova plugin ls
    cordova-custom-config 1.2.4 "cordova-custom-config"
    cordova-plugin-whitelist 1.0.0 "Whitelist"
    Daves-Mac:cordova-custom-config-example dave$ more platforms/ios/Custom\ config\ plugin\ example/Custom\ config\ plugin\ example-Info.plist
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>English</string>
        <key>CFBundleDisplayName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundleExecutable</key>
        <string>${EXECUTABLE_NAME}</string>
        <key>CFBundleIconFile</key>
        <string>icon.png</string>
        <key>CFBundleIcons</key>
        <dict/>
        <key>CFBundleIcons~ipad</key>
        <dict/>
        <key>CFBundleIdentifier</key>
        <string>uk.co.workingedge.phonegap.plugins.example.customconfig</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>0.0.1</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>0.0.1</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>NSMainNibFile</key>
        <string></string>
        <key>NSMainNibFile~ipad</key>
        <string></string>
        <key>UIRequiresFullScreen</key>
        <true/>
        <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSAllowsArbitraryLoads</key>
          <true/>
        </dict>
      </dict>
    </plist>
    Daves-Mac:cordova-custom-config-example dave$ cordova prepare ios
    cordova-custom-config: Installing plugin dependencies...
    cordova-custom-config: Installing plugin dependencies...
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/android/AndroidManifest.xml
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example.xcodeproj/project.pbxproj
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/cordova/build.xcconfig
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/cordova/build-extras.xcconfig
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/cordova/build-debug.xcconfig
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/cordova/build-release.xcconfig
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example/Custom config plugin example-Info.plist
    Daves-Mac:cordova-custom-config-example dave$ more platforms/ios/Custom\ config\ plugin\ example/Custom\ config\ plugin\ example-Info.plist
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>English</string>
        <key>CFBundleDisplayName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundleExecutable</key>
        <string>${EXECUTABLE_NAME}</string>
        <key>CFBundleIconFile</key>
        <string>icon.png</string>
        <key>CFBundleIcons</key>
        <dict/>
        <key>CFBundleIcons~ipad</key>
        <dict/>
        <key>CFBundleIdentifier</key>
        <string>uk.co.workingedge.phonegap.plugins.example.customconfig</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>0.0.1</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>0.0.1</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>NSMainNibFile</key>
        <string/>
        <key>NSMainNibFile~ipad</key>
        <string/>
        <key>UIRequiresFullScreen</key>
        <true/>
        <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSAllowsArbitraryLoads</key>
          <true/>
        </dict>
        <key>UISupportedInterfaceOrientations</key>
        <array>
          <string>UIInterfaceOrientationPortrait</string>
          <string>UIInterfaceOrientationPortraitUpsideDown</string>
        </array>
        <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
          <string>UIInterfaceOrientationPortrait</string>
          <string>UIInterfaceOrientationPortraitUpsideDown</string>
        </array>
        <key>UIBackgroundModes</key>
        <array>
          <string>location</string>
        </array>
        <key>NSLocationAlwaysUsageDescription</key>
        <string>This app requires constant access to your location in order to track your position, even when the screen is off.</string>
        <key>NSLocationWhenInUseUsageDescription</key>
        <string>This app will now only track your location when the screen is on and the app is displayed.</string>
      </dict>
    </plist>
    Daves-Mac:cordova-custom-config-example dave$

**Comment by johnkcox** [comment]
your example works but that still doesn't solve my problem, unfortunately. how does the backup feature work? any chance that the custom-config plugin is overwriting its changes with the backups? not really sure how it works...

**Comment by johnkcox** [comment]
ok more info. it's some kind of collision with phonegap-plugin-push. If we don't install that plugin we can write custom config-file preferences all day long. as soon as we add that plugin back in (which also writes to the *-Info.plist file) we are no longer able to add custom config-file entries with your plugin. however, i tried just adding that phonegap-plugin-push to your example project hoping it would break there too but it did not...

**Comment by dpa99c** [comment]
You can try disabling the [auto-backup/restore behaviour](https://github.com/dpa99c/cordova-custom-config#backups) of this plugin by adding the following preference to your config.xml:

    <preference name="cordova-custom-config-autorestore" value="false" />

**Comment by dpa99c** [comment]
@johnkcox this still an issue?

**Comment by dpa99c** [comment]
Re-open if still an issue

**Comment by theomathieubhvr** [comment]
Still same issue. This plugin is sadly not compatible with push from phonegap.

Thanks !
