### ISSUE TITLE
add in sugar for escaping

### ISSUE THREAD

**Issue by contra** [dpa99c/cordova-custom-config#4]
Example where this currently breaks:

```xml
<preference name="ios-XCBuildConfiguration-LD_RUNPATH_SEARCH_PATHS" value="@executable_path/Frameworks" />
```

needs to be changed to

```xml
<preference name="ios-XCBuildConfiguration-LD_RUNPATH_SEARCH_PATHS" value="&quot;@executable_path/Frameworks&quot;" />
```

or else it corrupts the pbxproj file

**Comment by contra** [comment]
Actually, just tried it: If you try to escape it in the XML cordova just logs "undefined" and crashes. Right now there is no workaround :(

**Comment by dpa99c** [comment]
Hi Eric, Thanks for raising these issues. I'm not ignoring them, just really busy right now. Will try to  make some time to investigate/fix sometime this week.
