### ISSUE TITLE
Quote configuration attribute for values not being respected

### ISSUE THREAD

**Issue by trigoesrodrigo** [dpa99c/cordova-custom-config#40]
When applying `quote="none"` or `quote="key"` to an ios preference, the value is always quoted when it shouldn't.

I think the error could be on https://github.com/dpa99c/cordova-custom-config/blob/1.2.5/hooks/applyCustomConfig.js#L400 . The value written is always `quoteEscape(item.value)` when it should be `value`.

**Comment by dpa99c** [comment]
oops, yes you are right. looks like I forgot to change line 400 to `block["buildSettings"][name] = value;`.
Will fix, bump version and push to npm. thanks for reporting it :+1:

**Comment by dpa99c** [comment]
pushed to npm as 1.2.6

**Comment by trigoesrodrigo** [comment]
Wow that was fast!

Thank you! ;)
