### ISSUE TITLE
Advanced documentation on preference formatting

### ISSUE THREAD

**Issue by xdoremus** [dpa99c/cordova-custom-config#43]
Very nice job, I am glad this plugin exists. :)

I can't find an easy way to map a field I want to modify to its name in the .plist for iOS.
For example, how can I access CFBundleDevelopmentRegion or CFBundleDisplayName ?

Thanks, and keep up the good work!

**Comment by dpa99c** [comment]
You just need to use the existing config file mechanism and set the parent to the root key name you want to override:

    <config-file platform="ios" target="*-Info.plist" parent="CFBundleDisplayName">
        <string>foo</string>
    </config-file>

    <config-file platform="ios" target="*-Info.plist" parent="CFBundleDevelopmentRegion">
        <string>Martian</string>
    </config-file>

**Comment by xdoremus** [comment]
Give that man a cookie!
Thanks a lot
