### ISSUE TITLE
AndroidManifest.xml not overwritten by the custom config

### ISSUE THREAD

**Issue by jperdereau** [dpa99c/cordova-custom-config#52]
Hello 😃 

In the config.xml I have this custom config to change `supports-screens` inside the AndroidManifest.xml

```
    <platform name="android">
        [.... more code]
        <config-file target="AndroidManifest.xml" parent="/*">
            <supports-screens android:smallScreens="false"
                              android:normalScreens="false"
                              android:largeScreens="true"
                              android:xlargeScreens="true"
                              android:requiresSmallestWidthDp="600" />
        </config-file>
    </platform>
```

after each `cordova prepare` I still have the default value and the custom one is every time added as well
```
<supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />

[.... more code]


<supports-screens android:largeScreens="true" android:normalScreens="false" android:requiresSmallestWidthDp="600" android:smallScreens="false" android:xlargeScreens="true" />
<supports-screens android:largeScreens="true" android:normalScreens="false" android:requiresSmallestWidthDp="600" android:smallScreens="false" android:xlargeScreens="true" />
```

**Comment by dpa99c** [comment]
This plugin currently doesn't analyse the child node contents defined within a `<config-file>` block, it simply injects them verbatim into the parent node. Therefore, constraints such as conditionally replacing/merging with an existing element (note that other elements such as `<uses-permission>` *are* allowed multiple times) will not be applied - a new element will simply be injected.

In this specific case, you can work around this by using preferences to add/modify attributes on the existing element, for example:

    <preference name="android-manifest/supports-screens/@android:smallScreens" value="false" />

**Comment by dpa99c** [comment]
Reopen if above solution doesn't work

**Comment by jperdereau** [comment]
i found something with what you suggested thx a lot 👍
