### ISSUE TITLE
Preference code is run even though it's included in non-executing platform block

### ISSUE THREAD

**Issue by Caine72** [dpa99c/cordova-custom-config#53]
Developing in visual studio 2015 for both Android and iOS.

When building for Android only the preference in the iOS platform block is still run.
i.e.
```
<platform name="ios">
<preference name="ios-XCBuildConfiguration-ENABLE_BITCODE" value="NO" />`
<platform>
```
This does not seem to occur when it comes to configuration blocks.
When the update error occurs, compilation for android breaks.

 `<preference name="cordova-custom-config-stoponerror" value="false"/>` does not seem to remedy the issue. 

As far as I can tell , the reason why the error occurs is because the file does not exist on the currently executing system, and it executes fine when building for iOS specifically as then the plugin is executed and run remotely on our Mac-buildmachine.

So have i stumbled up on a bug or is this working as intended?

**Comment by dpa99c** [comment]
The current behaviour is that the `after_prepare` script iterates over each platform for which a project directory is present under the `platforms/` directory ([see here in the source code](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L565)). 

So does this mean you have the `platforms/ios` directory present on a machine which doesn't support the iOS build environment?

**Comment by Caine72** [comment]
Yes pretty much so it seems. Microsoft seem to have made their solutions so that some files do pre-exist on the machine your writing your code on (and are copied over when building), but some are created(exists) solely on the remote build machine (TACO-remotebuild) env.

E.g the *-Info.plist exists, but the *.xcodeproj does not. 
I'm guessing this preference goes into the later?

So when executing the Android builds. which is solely run on Win-machine, the execution is stopped when it cannot find the *.xcodeproj.

**Comment by Caine72** [comment]
Oh dear. This is embarrassing. Was able to reproduce this all day yesterday. Today after setting up the project from scratch again ... not so much... must have been some local corruption .. 

Thanks for the fast reply and I'm so sorry for wasting your time!

**Comment by dpa99c** [comment]
No problem, every developer has days like that! I appreciate your honesty - many people would just leave the issue hanging. Please re-open if you find there is an issue though - I don't use Visual Studio so would be unaware if any issues arose from its use with this plugin.
