### ISSUE TITLE
Build error when following example in readme: No resource found that matches the given name (at 'value' with value '@android:style/Theme.Red.NoTitleBar')

### ISSUE THREAD

**Issue by skhouseholder** [dpa99c/cordova-custom-config#56]
I'm trying to get this plugin working with the ultimate goal of changing the theme to Material Dark on Android. I started by trying to change the theme to the one used in your example config.xml, but I get the following build error: 

`:processDebugResources/Users/sarah/Development/myapp/platforms/android/res/xml/config.xml:21:84-119 : AAPT: No resource found that matches the given name (at 'value' with value '@android:style/Theme.Red.NoTitleBar')`

I incorporated the items from your readme one at a time, and I was able to build and run my app successfully after making the following two:

1. Adding the Android namespace attribute. Mine now looks like this:

```
<widget 
    id="com.asdfasdfasdf.myapp" 
    version="2.0.2" 
    xmlns="http://www.w3.org/ns/widgets" 
    xmlns:cdv="http://cordova.apache.org/ns/1.0" 
    xmlns:android="http://schemas.android.com/apk/res/android"
    >

```

2. I added the autorestore setting as per your instructions. Like so:

```
<widget 
    id="com.bla.myapp" 
    version="2.0.2" 
    xmlns="http://www.w3.org/ns/widgets" 
    xmlns:cdv="http://cordova.apache.org/ns/1.0" 
    xmlns:android="http://schemas.android.com/apk/res/android"
    >
    <name>bla</name>
    <description>
        Bla
    </description>
    <author email="bla@gmail.com" href="http://www.bla.com">
        bla
    </author>
    <content src="index.html" />

    <!-- from https://github.com/dpa99c/cordova-custom-config#removable-preferences-via-backuprestore -->
    <preference name="cordova-custom-config-autorestore" value="true" />

    <preference name="android-minSdkVersion" value="19" />
    ...

```

Once everything built and ran properly with those changes, I added one of the lines from your Android example to my config.xml. Here's the entire Android section of config.xml:

```
<platform name="android">
        
        <preference name="android-manifest/application/activity/@android:theme" value="@android:style/Theme.Red.NoTitleBar" />

        <allow-intent href="market:*" />
        <icon src="www/res/icon/android/icon_48_mdpi.png" density="ldpi" />
        <icon src="www/res/icon/android/icon_48_mdpi.png" density="mdpi" />
        <icon src="www/res/icon/android/icon_72_hdpi.png" density="hdpi" />
        <icon src="www/res/icon/android/icon_96_xhdpi.png" density="xhdpi" />
        <icon src="www/res/icon/android/icon_144_xxhdpi.png" density="xxhdpi" />
        <icon src="www/res/icon/android/icon_192_xxxhdpi.png" density="xxxhdpi" />

</platform>


```

After adding that, building gives me the error I mentioned above:

`:processDebugResources/Users/sarah/Development/myapp/platforms/android/res/xml/config.xml:21:84-119 : AAPT: No resource found that matches the given name (at 'value' with value '@android:style/Theme.Red.NoTitleBar')`

Can you point me in the right direction? I'm not sure what I'm doing wrong. I'm running on a Nexus 6P with Android Marshmallow. Cordova is 6.2.0 and the Android platform version is 5.1.1.

Also, thank you for making this plugin! It looks excellent and well documented, and I look forward to getting it working. =)

**Comment by dpa99c** [comment]
Ah, sorry, this is down to my non-obvious example: `Theme.Red.NoTitleBar` is not actually a default Android theme, so to actually use that theme, you'd first need to define it in the various `styles.xml` files (see the [Android themes docs](https://developer.android.com/guide/topics/ui/themes.html)).

To set the default Material Dark theme, try:

    <preference name="android-manifest/application/activity/@android:theme" value="@android:style/Theme.Material" />

**Comment by skhouseholder** [comment]
Great. Thanks for the quick and helpful reply!
