### ISSUE TITLE
ios-PBXProject-DevelopmentTeam doesn't work

### ISSUE THREAD

**Issue by panaggio** [dpa99c/cordova-custom-config#62]
To set the Team on a target, you need to set `DevelopmentTeam` on `PBXProject`. But setting `ios-PBXProject-DevelopmentTeam` doesn't work.

http://imgur.com/MmQkVwy

**Comment by dpa99c** [comment]
As [stated in the documentation](https://github.com/dpa99c/cordova-custom-config#build-configuration-preferences):

> Currently, `XCBuildConfiguration` is the only supported block type in the `project.pbxproj`.

When I get some time, I will continue with the rewrite of this plugin which, among other things, will support arbitrary block types in the `project.pbxproj`,

**Comment by SquadraCorse** [comment]
You can simply use a hook for setting your team right. See https://dpogue.ca/articles/cordova-xcode8.html

**Comment by dpa99c** [comment]
As of cordova-ios@4.3.0, you don't need a hook as development team is supported in build.json: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#using-flags

In fact, on that basis, I'm closing this issue.
