### ISSUE TITLE
How to add/change value of theme

### ISSUE THREAD

**Issue by royipressburger** [dpa99c/cordova-custom-config#66]
Hi

Currently android have a default value on `textAllCaps` which cause a some texts to be all caps, link in `<button>`.

after reading around I found that the solutions in android is very simple: 
`android:textAllCaps="false"` this needs to applied under theme I think..

Is there a way to add that via this plugin?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-custom-config#android):

> The plugin currently supports setting of custom config only in `platforms/android/AndroidManifest.xml`

Since the `textAllCaps` will be set on an element in a different XML file, this plugin will not (currently) help with this.
