### ISSUE TITLE
Inserting node of the same name in AndroidManifest.xml

### ISSUE THREAD

**Issue by hx-markterry** [dpa99c/cordova-custom-config#67]
The config below only adds the last `intent-filter` node, not all three.

```
        <config-file target="AndroidManifest.xml" parent="./application/activity">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:host="com.example.ex1" android:scheme="ex" />
            </intent-filter>
         </config-file>
```

**Comment by FdezRomero** [comment]
I'm having exactly the same issue as @hx-markterry. Any help?

**Comment by kasperbauer** [comment]
Just the same over here...

**Comment by fabledfoe** [comment]
Can confirm the same behavior. Really disappointing as it undercuts the entire usefulness of the plugin having to manually add it myself.  An option for insert/append would be nice, rather than replacing the entire node, then it wouldn't be necessary to repeat the original intent-filter tags within the config-file block.

**Comment by dicearr** [comment]
I've experienced the same issue.

**Comment by birbilis** [comment]
@dicearr indeed, seems it bit you here: https://forum.ionicframework.com/t/apk-installable-but-not-runnable/63635

**Comment by FdezRomero** [comment]
Good news! 😎 

I was checking the code and the plugin actually supports to have more than one intent filter, with some conditions:
- The `parent` **must be exactly** `./application/activity/[@android:name='MainActivity']`.
- Every `intent-filter` **must have** a unique `android:label` attribute.

Example:
```
<config-file target="AndroidManifest.xml" parent="./application/activity/[@android:name='MainActivity']">
    <intent-filter android:label="A UNIQUE LABEL HERE">
        <action android:name="android.intent.action.SEND" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="text/plain" />
    </intent-filter>
</config-file>
```

This will keep the `LAUNCHER` intent filter automatically set by Cordova (I was having the same problem as @dicearr).

I think this should be mentioned in the README, as it is a fairly common use case.

**Comment by dpa99c** [comment]
Resolved in `cordova-custom-config@3` - see the [example project](https://github.com/dpa99c/cordova-custom-config-example) for example
