### ISSUE TITLE
lodash@3 discontinued support makes the plugin fail with other plugins/grunt plugins

### ISSUE THREAD

**Issue by fcamblor** [dpa99c/cordova-custom-config#69]
Hi,

I'm currently using `cordova-custom-config` in a grunt project where I have some grunt plugins requiring `lodash@3` to work properly (typically, `usemin` plugin)

I forced `lodash@3` usage into my `package.json` : when I `npm install`, `lodash@3` is installed into my `node_modules`, that's perfect (and my build works fine).

However, as soon as I `cordova build` (and thus, trigger `cordova-custom-config` plugin), my `node_modules/lodash/` version is updated to `lodash@4`, making my next call to `grunt usemin`  to fail.

I tried using `cordova-custom-config@1.2.3` (version before a563d05ea63731a659c6087610fdf90fb5c3b514 which dropped `lodash@3` compat in the plugin), however, at this version, there is a `lodash:*` defined version into the plugin, which grabs `lodash@4` nowadays.

Would you consider making a legacy branch starting from tag `1.2.3` and simply putting a `lodash:3.10.1` (for instance) allowing us to reference it and not clutter our cordova installation ?
It would be very kind.

Regards,

**Comment by dpa99c** [comment]
I'm not really keen to create/maintain another branch for this specific edge case, so I'd suggest you fork the plugin and make the required changes to the plugin's `package.json`.
