### ISSUE TITLE
Error: Cannot find module '''fs-extra'''

### ISSUE THREAD

**Issue by bash88** [dpa99c/cordova-custom-config#7]
Cordova CLI fails on this error. I just installed the plugin via CLI and put in some orientation settings for iOS.

Am I missing anything?

Regards,
Bas

**Comment by bash88** [comment]
Hi Dave,

Never mind, this one's resolved. Turns out I had to npm install all required plugins and modules. Maybe this should be somewhere in the manual. Or did I just not read enough?

Regards,
Bas

**Comment by dpa99c** [comment]
The plugin should automatically install the required modules. If you had to do that manually with `npm install`, then I've definitely introduced a bug. I'll investigate further so reopening this until I've had a chance to look into it.

**Comment by andybb** [comment]
Same problem here. Installing cordova-custom-config@1.1.2 works.

**Comment by dpa99c** [comment]
Retested this with v1.1.4 and it works fine. Note that the log output will report that modules can't be found, but will then install them. Here's the console output:

    Daves-Mac:cordova-custom-config-example dave$ cordova plugin add cordova-custom-config
    Fetching plugin "cordova-custom-config@1" via npm
    Installing "cordova-custom-config" for ios
    Can't find module read-package-json, running npm install
    Module read-package-json is installed
    Can't find module lodash, running npm install
    Module lodash is installed
    Can't find module elementtree, running npm install
    Module elementtree is installed
    Can't find module plist, running npm install
    Module plist is installed
    Can't find module xcode, running npm install
    Module xcode is installed
    Can't find module tostr, running npm install
    Module tostr is installed
    Can't find module fs-extra, running npm install
    Module fs-extra is installed
    All dependency modules are installed.
    Daves-Mac:cordova-custom-config-example dave$ cordova plugin ls
    cordova-custom-config 1.1.4 "cordova-custom-config"
    cordova-plugin-whitelist 1.0.0 "Whitelist"
    Daves-Mac:cordova-custom-config-example dave$ cordova prepare ios --verbose
    cordova-custom-config: Checking to see if there are backups to restore...
    Generating config.xml from defaults for platform "ios"
    Calling plugman.prepare for platform "ios"
    Preparing ios project
    Processing configuration changes for plugins.
    Iterating over installed plugins: [ 'cordova-plugin-whitelist', 'cordova-custom-config' ]
    Writing out cordova_plugins.js...
    Wrote out iOS Bundle Identifier to "uk.co.workingedge.phonegap.plugins.example.customconfig"
    Wrote out iOS Bundle Version to "0.0.1"
    iOS Product Name has not changed (still "Custom config plugin example")
    cordova-custom-config: Created backup directory: /Users/dave/Documents/projects/cordova-custom-config-example/plugins/cordova-custom-config/backup
    cordova-custom-config: Created backup platform directory: /Users/dave/Documents/projects/cordova-custom-config-example/plugins/cordova-custom-config/backup/ios
    cordova-custom-config: Backed up /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example.xcodeproj/project.pbxproj to /Users/dave/Documents/projects/cordova-custom-config-example/plugins/cordova-custom-config/backup/ios/project.pbxproj
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example.xcodeproj/project.pbxproj
    cordova-custom-config: Backed up /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example/Custom config plugin example-Info.plist to /Users/dave/Documents/projects/cordova-custom-config-example/plugins/cordova-custom-config/backup/ios/Custom config plugin example-Info.plist
    cordova-custom-config: Applied custom config from config.xml to /projects/cordova-custom-config-example/platforms/ios/Custom config plugin example/Custom config plugin example-Info.plist
    cordova-custom-config: Write to plist; key=UISupportedInterfaceOrientations; value=[
      'UIInterfaceOrientationPortrait',
      'UIInterfaceOrientationPortraitUpsideDown'
    ]
    cordova-custom-config: Write to plist; key=UISupportedInterfaceOrientations~ipad; value=[
      'UIInterfaceOrientationPortrait',
      'UIInterfaceOrientationPortraitUpsideDown'
    ]
    cordova-custom-config: Write to plist; key=UIBackgroundModes; value=[
      'location'
    ]
    cordova-custom-config: Write to plist; key=NSLocationAlwaysUsageDescription; value='This app requires constant access to your location in order to track your position, even when the screen is off.'
    cordova-custom-config: Write to plist; key=NSLocationWhenInUseUsageDescription; value='This app will now only track your location when the screen is on and the app is displayed.'
    cordova-custom-config: Write to plist; key=NSAppTransportSecurity; value={
      NSAllowsArbitraryLoads: true
    }
    cordova-custom-config: add XCBuildConfiguration key='ENABLE_BITCODE' to value='NO' for build type='Debug' in block='1D6058940D05DD3E006BFB54'
    cordova-custom-config: add XCBuildConfiguration key='ENABLE_BITCODE' to value='NO' for build type='Release' in block='1D6058950D05DD3E006BFB54'
    cordova-custom-config: add XCBuildConfiguration key='ENABLE_BITCODE' to value='NO' for build type='Debug' in block='C01FCF4F08A954540054247B'
    cordova-custom-config: add XCBuildConfiguration key='ENABLE_BITCODE' to value='NO' for build type='Release' in block='C01FCF5008A954540054247B'
    cordova-custom-config: replace XCBuildConfiguration key='IPHONEOS_DEPLOYMENT_TARGET' to value='7.0' for build type='Release' in block='1D6058950D05DD3E006BFB54'
    cordova-custom-config: replace XCBuildConfiguration key='IPHONEOS_DEPLOYMENT_TARGET' to value='7.0' for build type='Release' in block='C01FCF5008A954540054247B'
    Daves-Mac:cordova-custom-config-example dave$

**Comment by nartawak** [comment]
I've tested with 1.1.4 and 1.1.2 and sometime it works fine and sometime not. This bug really block my developement. Have you got same issue again ?
Node version : 0.12.4
Npm Version : 3.3.10
cordova version : 5.3.3

**Comment by sinedied** [comment]
It seems this bug is back: on Windows platform, Node v4, Cordova 6.2.0 and cordova-custom-config 2.0.2 I have the error.

Any ideas?
