### ISSUE TITLE
Error: Failed to fetch plugin cordova-custom-config via registry.

### ISSUE THREAD

**Issue by sangeethkumarsg** [dpa99c/cordova-custom-config#71]
Unable to fetch the plugin from npm. 

I ran the following command

`cordova plugin add cordova-custom-config@2.0.3`

I got error that

`Error: Failed to fetch plugin cordova-custom-config via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.`

I tried again by removing the version specification

`cordova plugin add cordova-custom-config`

Still the same issue..

**Comment by dpa99c** [comment]
The plugin is [registered with npm](https://www.npmjs.com/package/cordova-custom-config) under this name and installs correctly using the plugin ID `cordova-custom-config`:

![2016-09-23_151109](https://cloud.githubusercontent.com/assets/2345062/18786838/341428bc-81a0-11e6-8cab-1417f2068814.jpg)

As this error message says, this probably this is a connection problem.

**Comment by sangeethkumarsg** [comment]
I am still getting issue..

Here is the full error I am getting..

![screen shot 2016-09-23 at 8 18 03 pm](https://cloud.githubusercontent.com/assets/15649495/18790043/e913a5d8-81ca-11e6-9ae2-290e30d31485.png)

Previously I was able to install the plugin. So doubt if anything missing in my environment.

Can you please help me ?

Node version: 2.11.3
Cordova CLI : 6.1.1
Ionic CLI : 1.7.16
