### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-custom-config#72]
Is there some way to localize PLIST entries?

Maybe like this?

```
<config-file parent="NSLocationWhenInUseUsageDescription" target="*-Info.plist">
  <string xml:lang="en">{{=it.name}} can help you find your location</string>
</config-file>
```

I have no internal knowledge how ios and Android handle resource translation.

**Comment by dpa99c** [comment]
Localization of plist entries requires additional files to be added to the project (see [here](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html) and [here](http://stackoverflow.com/questions/25736700/how-to-localise-a-string-inside-the-ios-info-plist-file)). As such, I'd consider this outside of the current scope of this plugin. While you can manually achieve all this in Xcode, ideally a dedicated Cordova localization plugin could encapsulate the required logic but AFAIK no such plugin yet exists.
