### ISSUE TITLE
Why install the dependencies in such a way?

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-custom-config#73]
Doesn't Cordova take care of installing dependencies?
No other cordova plugin uses this technique used here with a hook. They just describe the dependencies in their package.json (like this plugin) and thats it.

Is there any (historical) reason to do it like this and can we remove it please if its superseded by cordovas functionality now?

**Comment by dpa99c** [comment]
Cordova doesn't take care of installing plugin dependencies. You can confirm this by cloning the plugin repo locally, commenting out lines [25](https://github.com/dpa99c/cordova-custom-config/blob/master/plugin.xml#L25) and [26](https://github.com/dpa99c/cordova-custom-config/blob/master/plugin.xml#L25) in the [plugin.xml](https://github.com/dpa99c/cordova-custom-config/blob/master/plugin.xml) and adding the local plugin to a new project: `cordova plugin add /path/to/cordova-custom-config`

The dependencies are specified in the plugin's [package.json](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json). It would be easy enough to run `npm install` in the scope to `your_project/plugins/cordova-custom-config` to have node install them to `your_project/plugins/cordova-custom-config/node_modules`. However, Cordova hook scripts run in the scope of `your_project/` so in order for the scripts to [require the node modules in the current scope](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L646), the [resolveDependencies script](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js) installs them to `your_project/node_modules`. The project may or may not have its own `your_project/package.json` so it's not safe to simply copy `your_project/plugins/cordova-custom-config/package.json` to `your_project/package.json`, hence the resolveDependencies script manually installs each required module in the scope of `your_project/`. This also ensures that any existing modules in `your_project/node_modules` are correctly handled by npm.

It may be possible to install them to `your_project/plugins/cordova-custom-config/node_modules` and require them by somehow specifying a sub-path, but if so, I don't know how. For example, `fs = require('./plugins/cordova-custom-config/fs-extra')` doesn't resolve when `your_project/plugins/cordova-custom-config/node_modules/fs-extra` is present.

Any suggestions on how the current implementation can be improved upon would be most welcome. A pull request implementing it - even more so :)

**Comment by pke** [comment]
Ah pity. I was under the impression the --fetch param of `cordova plugins add --fetch" would handle that. But it does something completely different, and I don't know what for it does save the plugins in `node_modules`. I'll experiment

**Comment by dpa99c** [comment]
Wow, I totally missed the [release of `cordova-fetch`](https://cordova.apache.org/news/2016/05/24/tools-release.html)! 

Might be that we can make use of that. Would be great to get rid of the resolveDependencies script. I will also look into it.

**Comment by dpa99c** [comment]
OK, it seems --fetch is doing the right thing in installing dependencies specified in the plugin's package.json. 
Currently, it seems to only work with plugins specified via a registry ID. 
Tried with a Github URL and the result was that, while the node module dependencies were resolved and installed, the plugin failed to be installed in `plugins/`:

    $ cordova -v
    6.3.1

    $ ls
    config.xml  platforms  plugins  regression_test  www

    $ cordova plugin add https://github.com/dpa99c/cordova-custom-config#no_deps_script --fetch
    Error: Failed to fetch plugin https://github.com/dpa99c/cordova-custom-config#no_deps_script via registry.
    Probably this is either a connection problem, or plugin spec is incorrect.
    Check your connection and plugin name/version/URL.
    Failed to get absolute path to installed module

    $ ls node_modules/
    balanced-match         fs.realpath  minimatch         shelljs
    base64-js              glob         node-uuid         simple-plist
    bplist-creator         graceful-fs  once              stream-buffers
    bplist-parser          inflight     path-is-absolute  tostr
    brace-expansion        inherits     pegjs             util-deprecate
    colors                 interpret    plist             wrappy
    concat-map             jsonfile     rechoir           xcode
    cordova-custom-config  klaw         resolve           xmlbuilder
    elementtree            lodash       rimraf            xmldom
    fs-extra               lodash-node  sax

    $ ls plugins
    android.json  cordova-plugin-whitelist  fetch.json
    
    $ cordova prepare android --verbose
    No scripts found for hook "before_prepare".
    Checking config.xml for saved platforms that haven't been added to the project
    Checking for any plugins added to the project that have not been installed in android platform
    No differences found between plugins added to project and installed in android platform. Continuing...
    Generating config.xml from defaults for platform "android"
    Wrote out Android application name to "Custom config plugin example"
    Wrote out Android package name to "uk.co.workingedge.phonegap.plugins.example.customconfig"
    This app does not have launcher icons defined
    updated project successfully
    No scripts found for hook "after_prepare".
    Checking config.xml for saved plugins that haven't been added to the project

**Comment by dpa99c** [comment]
`cordova-custom-config@3` now relies on the `cordova-fetch` mechanism to resolve dependencies. Custom resolution script has been got rid of. Let me know if any issues and will reopen.

**Comment by pke** [comment]
hmmm in your second to last post you show that there are errors when installing using `--fetch`. Have these been solved?

**Comment by dpa99c** [comment]
The errors only occur if installing using a GitHub URL instead of a plugin id. But since v3 is published to npm, there's no reason to use a GitHub URL

**Comment by pke** [comment]
Ah cool. Understood. Any idea how this work with them `plugin add --save`?

**Comment by dpa99c** [comment]
From the [cordova-fetch source code](https://github.com/apache/cordova-lib/blob/master/cordova-fetch/index.js#L67) if appears that `--save` is passed on to `npm install` so plugin package name will be added to `package.json`. Curious to know if, when you make a subsequent clean checkout, running `npm install` triggers some Cordova-specific hook to install the plugins to `plugins/` and `platforms/` as well as into `node_modules/`. I think that needs some empirical testing.
