### ISSUE TITLE
Error when adding cordova-custom-config@3.0.13

### ISSUE THREAD

**Issue by eyalhakim** [dpa99c/cordova-custom-config#80]
npm ERR! cordova-custom-config@3.0.13 preinstall: `npm install check-node-version && check-node-version --npm ">=3"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cordova-custom-config@3.0.13 preinstall script 'npm install check-node-version && check-node-version --npm ">=3"'.

I ran the command myself and it works - returns the current node and npm versions.

Node: 7.0.0
NPM: 4.0.1
Cordova: 6.4.0

Thanks

**Comment by eyalhakim** [comment]
I made some progress:

npm install cordova-custom-config

> cordova-custom-config@3.0.13 preinstall /Users/eyalhakim/dev/repos/learni-app/node_modules/.staging/cordova-custom-config-986c4b7d
> npm install check-node-version && check-node-version --npm ">=3"

check-node-version@1.1.2 node_modules/check-node-version
├── semver@5.3.0
├── run-parallel@1.1.6
└── minimist@1.2.0
node: v7.0.0
npm: v2.15.11
Error: Wanted npm version ">=3" (>=3.0.0)
To install npm, run `npm install -g npm@>=3`
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "cordova-custom-config"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE

How is it possible that the output of check-node-version for npm is 2.15.11 when run from the preinstall script whereas when i run check-node-version the output says 4.0.1?
Also, you can see in the log that indeed npm v4.0.1 is running.

**Comment by eyalhakim** [comment]
i did every possible reinstallation of node and npm including https://github.com/brock/node-reinstall

**Comment by dpa99c** [comment]
Damn it, #79 fixed it for Windows and broke it for OSX. I'm just gonna remove the npm@3 version check and folks will have to just read the documentation.

**Comment by dpa99c** [comment]
Published to npm as `cordova-custom-config@3.0.14`

**Comment by eyalhakim** [comment]
Great, thank man!
