### ISSUE TITLE
Cordova 6.4.0 adds edit-config

### ISSUE THREAD

**Issue by JTronLabs** [dpa99c/cordova-custom-config#81]
It looks like the newest Cordova adds the ability to edit configs in the same manner that this plugin does. Maybe it would be good to add something to the README about this? - [6.4.0](https://cordova.apache.org/news/2016/10/25/tools-release.html) [Cordova new feature](https://issues.apache.org/jira/browse/CB-11908) [edit-config docs](http://cordova.apache.org/docs/en/6.x/plugin_ref/spec.html#edit-config)

**Comment by sinedied** [comment]
Does the new `<edit-config>` also works with iOS plist files? From the docs it does not seems so...

**Comment by dpa99c** [comment]
`<edit-config>` is similar to the [Android `<preference>`](https://github.com/dpa99c/cordova-custom-config#android-preferences) implemented by this plugin.

> Instead of appending new children to an XML document tree, `edit-config` makes modifications to attributes of XML elements. 

It does not operate on iOS .plist or .xcconfig files.

AFAIK, Cordova still doesn't support `config-file` blocks in the config.xml.

However, for completeness, I'll add a note under the [Android preferences](https://github.com/dpa99c/cordova-custom-config#android-preferences) section regarding `edit-config`
