### ISSUE TITLE
Allow for updating Entitlements-Release.plist and Entitlements-Debug.plist

### ISSUE THREAD

**Issue by aoathout** [dpa99c/cordova-custom-config#85]
With cordova-ios 4.3.0 two new plist files have been introduced to handle entitlements. Currently this plugin only allows for updating the *-Info.plist file and the project.pbxproj for iOS. It is desirable to have these files updated from entries inside the config.xml 

Pull Request is: #84

**Comment by dpa99c** [comment]
Added fix in `cordova-custom-config@3.1.0`.

**Comment by pke** [comment]
@dpa99c @aoathout I tried to use that:

```
<config-file platform="ios" target="Entitlements-Release.plist" parent="aps-environment" mode="replace">
          <string>production</string>
        </config-file>
        <config-file platform="ios" target="Entitlements-Debug.plist" parent="aps-environment" mode="replace">
          <string>development</string>
        </config-file>
```

But I still have to manually switch on the Push Notifications in xcode capabilities. I'd like to be able to build the ipa without opening xcode.

**Comment by spike-global** [comment]
Is there a way to automatically switch on the Push Notifications in xcode capabilities?

**Comment by qpwr** [comment]
My Entitlements-Debug/-Release.plist looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.device.bluetooth</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-only</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
  </dict>
</plist>
```

I want to make sure that no entitlement is missing when re-adding the iOS platform and am thus trying to set them through my config.xml. But since there is no parent key/element that I can use, I can't do it with anything like this:

```
<config-file platform="ios" parent="" target="Entitlements-Debug.plist" mode="replace">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <true/>
        <key>test</key>
        <false/>
        <key>com.apple.security.device.bluetooth</key>
        <true/>
        <key>com.apple.security.device.camera</key>
        <true/>
        <key>com.apple.security.files.user-selected.read-only</key>
        <true/>
        <key>com.apple.security.network.client</key>
        <true/>
        <key>com.apple.security.network.server</key>
        <true/>
    </dict>
</config-file>
```

Any advice, @dpa99c?

**Comment by qpwr** [comment]
JFYI, if anyone runs into the same issue: My workaround now is to add each key separately, which works as expected.
