### ISSUE TITLE
Refusing to install cordova-custom-config as a dependency of itself

### ISSUE THREAD

**Issue by Chaotize** [dpa99c/cordova-custom-config#86]
call cordova plugin add cordova-custom-config --save

Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" for android
cordova-custom-config: npm dependencies missing - installing
Failed to install 'cordova-custom-config':undefined
Error: Error installing npm dependencies: Error: Command failed: npm install cordova-custom-config
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{USER}\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova-custom-config"
npm ERR! node v5.7.1
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install cordova-custom-config as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Cordova_Projects\{Project}\npm-debug.log

I have replaced username and projectname but its the output I get if I try to install the plugin

**Comment by dpa99c** [comment]
Is "projectname" called "cordova-custom-config" ?? 
This would explain the error - [see here](http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/)

**Comment by Chaotize** [comment]
"projectname" is not called "cordova-custom-config". It seems to work if I add the plugin on a fresh project:

Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" for windows
cordova-custom-config: npm dependencies missing - installing
cordova-custom-config: Installed npm dependencies
Saved plugin info for "cordova-custom-config" to config.xml

**Comment by dpa99c** [comment]
It's not an error I've come across or has been reported before, so not sure what could be causing it.
I'd recommend making sure node_modules/cordova-custom-config and plugins/cordova-custom-config are not already present - if they are, delete them. Then try a fresh install.
Also, try installing directly as an npm module via the [new cordova-fetch method](https://cordova.apache.org/news/2016/05/24/tools-release.html):

    cordova plugin add cordova-custom-config --fetch --save
