### ISSUE TITLE
config flag to disable backup

### ISSUE THREAD

**Issue by contra** [dpa99c/cordova-custom-config#9]
the backup functionality is really problematic if you are making manual changes to the xcode config

**Comment by regnete** [comment]
Same for me. We delete the backupfolder before every run via subroutine in our buildscripts.


Felix

Am 31.10.2015 um 17:58 schrieb contra <notifications@github.com<mailto:notifications@github.com>>:


the backup functionality is really problematic if you are making manual changes to the xcode config

-

**Comment by dpa99c** [comment]
Fixed by 5ee92d1ccf310f585ce57767dc8940fb077c89b4
