### ISSUE TITLE
Error reading plist in xcode 8.1

### ISSUE THREAD

**Issue by rtaschetto** [dpa99c/cordova-custom-config#95]
After apply custom-config for ios , if I open plist file in Xcode 8.1 i have this error: "The data couldn’t be read because it isn’t in the correct format."

this is my config.xml:

`  <preference name="cordova-custom-config-autorestore" value="false" />
    <preference name="cordova-custom-config-stoponerror" value="true" />
    <preference name="cordova-custom-config-hook" value="after_prepare" />
...
    <platform name="ios">
        
        <config-file platform="ios" target="*-Info.plist" parent="LSApplicationQueriesSchemes">
          <array>
            <string>whatsapp</string>
          </array>
        </config-file>
    </platform name="ios">
`

I notice that in generated plist files there is some key different from previous plist file. For example:
    <key>NSMainNibFile</key>
    <key>NSMainNibFile~ipad</key>
became:
    <key>NSMainNibFile</key>
    <string>NSMainNibFile~ipad</string>

see attached file for complete plist file..

Thank you for any help you can give me,
Roberto

[KiSHER-Info.plist.zip](https://github.com/dpa99c/cordova-custom-config/files/618788/KiSHER-Info.plist.zip)

**Comment by dpa99c** [comment]
Running the extract from your config.xml against the example project with a clean iOS platform, I get the output below. As you can see it is very different from the zip file you posted and opens fine in Xcode 8.1. The plist you posted looks completely corrupt and I would suspect a missing closing tag has caused the custom config plugin to have problems parsing the (invalid) XML.
Do you have more custom config in your config.xml or additional plugins that are modifying the plist?


Output plist:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>English</string>
        <key>CFBundleDisplayName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundleExecutable</key>
        <string>${EXECUTABLE_NAME}</string>
        <key>CFBundleIcons</key>
        <dict/>
        <key>CFBundleIcons~ipad</key>
        <dict/>
        <key>CFBundleIdentifier</key>
        <string>uk.co.workingedge.phonegap.plugins.example.customconfig</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>${PRODUCT_NAME}</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>0.0.1</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>0.0.1</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>NSMainNibFile</key>
        <string/>
        <key>NSMainNibFile~ipad</key>
        <string/>
        <key>UISupportedInterfaceOrientations</key>
        <array>
          <string>UIInterfaceOrientationPortrait</string>
          <string>UIInterfaceOrientationLandscapeLeft</string>
          <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
          <string>UIInterfaceOrientationPortrait</string>
          <string>UIInterfaceOrientationLandscapeLeft</string>
          <string>UIInterfaceOrientationPortraitUpsideDown</string>
          <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UIRequiresFullScreen</key>
        <true/>
        <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSAllowsArbitraryLoads</key>
          <true/>
        </dict>
        <key>LSApplicationQueriesSchemes</key>
        <array>
          <string>whatsapp</string>
        </array>
      </dict>
    </plist>

**Comment by rtaschetto** [comment]
Hi Dave,
thank you for your feedback. I'll check as soon as possible.
I have one custom config, but i have many plugins. I'll check if one of thesemodify the p-list.

Thank you again,
Roberto
