### ISSUE TITLE
Setting the android:networkSecurityConfig and associated network_security_config

### ISSUE THREAD

**Issue by BrianJVarley** [dpa99c/cordova-custom-config#97]
Hi @dpa99c! I've used cordova-custom-config previously to set Android permissions from my Cordova project's config.xml without fail. 

But now I need to set `android:networkSecurityConfig="@xml/network_security_config"` and in turn create the associated `network_security_config.xml` file. Where I then want to specify ` <domain-config cleartextTrafficPermitted="false">` to prevent clear text traffic in line with security requirements.

Is it possible to achieve this with cordova-custom-config?
I know it's possible to create Config blocks with this plugin but only within AndroidManifest?

This is from the developer docs detailing how to opt out of clear text here ->
https://developer.android.com/training/articles/security-config.html and here -> https://code.google.com/p/android/issues/detail?id=212584

First the entry is added to the Application tag of AndroidManifest pointing to a network_security_config.xml file. 

`<application android:networkSecurityConfig="@xml/network_security_config" `

Then this file is added to `res/xml/network_security_config.xml`:

`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="true">secure.example.com</domain>
    </domain-config>
</network-security-config>`

**Comment by dpa99c** [comment]
You can set the `android:networkSecurityConfig` attribute on the `<application>` element using this plugin, but it currently [only supports modification of `AndroidManifest.xml`](https://github.com/dpa99c/cordova-custom-config#android) so you won't be able to add/modify `res/xml/network_security_config.xml` using this plugin.

One solution would be to create your own simple plugin which contains your `network_security_config.xml` file and references it in the `plugin.xml` something like:

    <platform name="android">
        <source-file src="network_security_config.xml" target-dir="res/xml" />
    </platform>

The plugin can be local - doesn't need to be in a repo. Then you can add it to your Cordova project which will copy your XML file to the correct location under `platforms/android/`.
