### ISSUE TITLE
Info.plist not updated

### ISSUE THREAD

**Issue by mirko77** [dpa99c/cordova-custom-config#98]
Hi there, I am trying to add a couple of usage descriptions (Photo Library, Microphone) to my .plist file using:

```
 <!-- Set message displayed when app requests microphone -->
 <config-file platform="ios" target="*-Info.plist" parent="NSMicrophoneUsageDescription">
    <string>This app requires access to your microphone to function properly.</string>
 </config-file>

 <!-- Set message displayed when app requests photo gallery -->
 <config-file platform="ios" target="*-Info.plist" parent="NSPhotoLibraryUsageDescription">
     <string>This app requires access to your photo gallery to function properly.</string>
 </config-file>
```

the log looks successful:

```
cordova-custom-config: Running applyCustomConfig.js
cordova-custom-config: Loaded module dependencies
cordova-custom-config: Backup exists for 'Epicollect5-Info.plist' at: /Users/Mirko/Sites/epicollect5-mobile-app/plugins/cordova-custom-config/backup/ios/Epicollect5-Info.plist
cordova-custom-config: Applied custom config from config.xml to /Users/Mirko/Sites/epicollect5-mobile-app/platforms/ios/Epicollect5/Epicollect5-Info.plist
cordova-custom-config: Write to plist; key=NSMicrophoneUsageDescription; value='This app requires access to your microphone to function properly.'
cordova-custom-config: Write to plist; key=NSPhotoLibraryUsageDescription; value='This app requires access to your photo gallery to function properly.'
cordova-custom-config: Finished applying platform config

```

but when I look at the Info.plist, those descriptions are not added:
![screen shot 2017-01-20 at 13 55 40](https://cloud.githubusercontent.com/assets/1233305/22151923/35232cfa-df18-11e6-9dc3-84f831f7e903.png)

Am I missing something?

**Comment by dpa99c** [comment]
Since those keys are present in your Info.plist, but with a different message, it may that another plugin is overwriting the values set by this plugin. Check which other plugins you have installed in your project and if any of those are setting these keys in their `plugin.xml`.

You can check that the plugin works properly in isolation using the [example project](https://github.com/dpa99c/cordova-custom-config-example)

**Comment by dpa99c** [comment]
Sorry, I misread your screenshot: I see that the keys are present for those keys, but contains empty strings.

**Comment by dpa99c** [comment]
Still, the same applies: check that no other plugin is setting an empty message for these keys.
Also try your config blocks within the example project.

**Comment by mirko77** [comment]
Thanks for your help. I will look into it then

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by mirko77** [comment]
Haven't got the chance to look at it, sorry. Let's close it for now

**Comment by mirko77** [comment]
Found the offending plugin. All fixed.

**Comment by jcdickman** [comment]
@mirko77 Having this same issue, which plugin created the problem for you?

**Comment by mirko77** [comment]
@jcdickman for me it was the barcode scanner plugin

**Comment by jcdickman** [comment]
:-( not using that one lol. If I track down the one messing me up I'll post it here. Since it's only an inconvenience (having to manually add that before submission to app store) not sure when I'll get to it. Thank you for the quick assist though @mirko77.

**Comment by mirko77** [comment]
@jcdickman look inside `/plugins`, open all the `.json` files, they might give you a hint. 
I found mine this way

**Comment by dpa99c** [comment]
@jcdickman as @mirko77 said, but also look at the `plugin.xml` for each plugin and look for `<config-file>` blocks that insert empty keys. If you don't find any, look for plugin hook scripts that may also inject these programatically.
